# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('SHORT_INPUT_TEXT', 'short_input_text'), ('LONG_INPUT_TEXT', 'long_input_text'), ('RADIO_BUTTON', 'radio_button'), ('CHECKBOX', 'checkbox'), ('DROPDOWN_LIST', 'dropdown_list'), ('UPLOAD_BUTTON', 'upload_button'), ('DOWNLOAD_LINK', 'download_link'), ('HTTP_LINK', 'http_link')], max_length=20),
        ),
    ]
