# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-28 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0005_auto_20170221_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
