# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='scoresencoding',
            table=None,
        ),
    ]
