# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0148_auto_20170821_0931'),
        ('reference', '0016_auto_20170410_1318'),
        ('assessments', '0002_auto_20170428_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreSheetAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_address_choice', models.CharField(blank=True, choices=[('ENTITY_ADMINISTRATION', 'ENTITY_ADMINISTRATION'), ('ENTITY_ADMINISTRATION_PARENT', 'ENTITY_ADMINISTRATION_PARENT'), ('ENTITY_MANAGEMENT', 'ENTITY_MANAGEMENT'), ('ENTITY_MANAGEMENT_PARENT', 'ENTITY_MANAGEMENT_PARENT')], max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
                ('offer_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear')),
            ],
        ),
    ]
