# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_scoresheetaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheetaddress',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='scoresheetaddress',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scoresheetaddress',
            name='recipient',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
