# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 10:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160114_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examenrollment',
            old_name='justification',
            new_name='justification_draft',
        ),
        migrations.RenameField(
            model_name='examenrollment',
            old_name='score',
            new_name='score_draft',
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='justification_final',
            field=models.CharField(blank=True, choices=[('ABSENT', 'Absent'), ('CHEATING', 'Cheating'), ('ILL', 'Ill'), ('JUSTIFIED_ABSENCE', 'Justified absence'), ('SCORE_MISSING', 'Score missing')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='justification_reencoded',
            field=models.CharField(blank=True, choices=[('ABSENT', 'Absent'), ('CHEATING', 'Cheating'), ('ILL', 'Ill'), ('JUSTIFIED_ABSENCE', 'Justified absence'), ('SCORE_MISSING', 'Score missing')], max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='score_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='examenrollment',
            name='score_reencoded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(0)]),
        ),
    ]
