# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160114_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicyear',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='event_type',
            field=models.CharField(choices=[('ACADEMIC_YEAR', 'Academic Year'), ('DISSERTATIONS_SUBMISSION_SESS_1', 'Submission of academic dissertations - exam session 1'), ('DISSERTATIONS_SUBMISSION_SESS_2', 'Submission of academic dissertations - exam session 2'), ('DISSERTATIONS_SUBMISSION_SESS_3', 'Submission of academic dissertations - exam session 3'), ('EXAM_SCORES_SUBMISSION_SESS_1', 'Submission of exam scores - exam session 1'), ('EXAM_SCORES_SUBMISSION_SESS_2', 'Submission of exam scores - exam session 2'), ('EXAM_SCORES_SUBMISSION_SESS_3', 'Submission of exam scores - exam session 3'), ('DELIBERATIONS_SESS_1', 'Deliberations - exam session 1'), ('DELIBERATIONS_SESS_2', 'Deliberations - exam session 2'), ('DELIBERATIONS_SESS_3', 'Deliberations - exam session 3'), ('EXAM_SCORES_DIFFUSION_SESS_1', 'Diffusion of exam scores - exam session 1'), ('EXAM_SCORES_DIFFUSION_SESS_2', 'Diffusion of exam scores - exam session 2'), ('EXAM_SCORES_DIFFUSION_SESS_3', 'Diffusion of exam scores - exam session 3'), ('EXAM_ENROLLMENTS_SESS_1', 'Exam enrollments - exam session 1'), ('EXAM_ENROLLMENTS_SESS_2', 'Exam enrollments - exam session 2'), ('EXAM_ENROLLMENTS_SESS_3', 'Exam enrollments - exam session 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='external_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='event_type',
            field=models.CharField(choices=[('ACADEMIC_YEAR', 'Academic Year'), ('DISSERTATIONS_SUBMISSION_SESS_1', 'Submission of academic dissertations - exam session 1'), ('DISSERTATIONS_SUBMISSION_SESS_2', 'Submission of academic dissertations - exam session 2'), ('DISSERTATIONS_SUBMISSION_SESS_3', 'Submission of academic dissertations - exam session 3'), ('EXAM_SCORES_SUBMISSION_SESS_1', 'Submission of exam scores - exam session 1'), ('EXAM_SCORES_SUBMISSION_SESS_2', 'Submission of exam scores - exam session 2'), ('EXAM_SCORES_SUBMISSION_SESS_3', 'Submission of exam scores - exam session 3'), ('DELIBERATIONS_SESS_1', 'Deliberations - exam session 1'), ('DELIBERATIONS_SESS_2', 'Deliberations - exam session 2'), ('DELIBERATIONS_SESS_3', 'Deliberations - exam session 3'), ('EXAM_SCORES_DIFFUSION_SESS_1', 'Diffusion of exam scores - exam session 1'), ('EXAM_SCORES_DIFFUSION_SESS_2', 'Diffusion of exam scores - exam session 2'), ('EXAM_SCORES_DIFFUSION_SESS_3', 'Diffusion of exam scores - exam session 3'), ('EXAM_ENROLLMENTS_SESS_1', 'Exam enrollments - exam session 1'), ('EXAM_ENROLLMENTS_SESS_2', 'Exam enrollments - exam session 2'), ('EXAM_ENROLLMENTS_SESS_3', 'Exam enrollments - exam session 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='external_id',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.OfferYear'),
        ),
    ]
