# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-17 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160117_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='decimal_scores',
            field=models.BooleanField(default=False),
        ),
    ]
