# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models


def create_trigger_for_changed_field(table_name):
    """
    Crée et renvoie un code sql qui crée trigger pour le champs "changed"
    dans la table/modèle passée en paramètre.

    :param table_name: Nom de la table/modèle dans laquelle il faut créer un trigger.
    """
    table_name = table_name.lower()
    return "CREATE TRIGGER update_" + table_name + "_modtime BEFORE UPDATE ON core_" + table_name + " FOR EACH ROW EXECUTE PROCEDURE update_changed_column();"



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160122_1201'),
    ]

    operations = [
        migrations.RunSQL(
        """CREATE OR REPLACE FUNCTION update_changed_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.changed = now();
            RETURN NEW;
        END;
        $$ language 'plpgsql';"""
        ),

        migrations.RunSQL(
            create_trigger_for_changed_field('person'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('tutor'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('student'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('organization'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('structure'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('programmemanager'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('academicyear'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('academiccalendar'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offer'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offeryear'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offerenrollment'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offeryearcalendar'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('learningunit'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('attribution'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('learningunityear'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('learningunitenrollment'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('sessionexam'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('examenrollment'),
        )
    ]
