# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0015_educationinstitution_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('published', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.TextLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(db_index=True, max_length=100)),
                ('reference', models.IntegerField(db_index=True)),
                ('text', models.BinaryField(null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('text_label', models.ForeignKey(blank=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cms.TextLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedTextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('text_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.TextLabel')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='textlabel',
            unique_together=set([('parent', 'order')]),
        ),
    ]
