# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20170316_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textlabel',
            name='order',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
