# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20170425_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlabel',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='textlabel',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='translatedtext',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='translatedtext',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='translatedtextlabel',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='translatedtextlabel',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
