# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20170516_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatedtext',
            name='language',
            field=models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='translatedtextlabel',
            name='language',
            field=models.CharField(choices=[('fr-be', 'French'), ('en', 'English')], default='fr-be', max_length=30, null=True),
        ),
    ]
