from reference.models.enums import domain_type
from reference.models.enums import education_institution_national_comunity
from reference.models.enums import education_institution_type
from reference.models.enums import grade_type_coverage