# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-01-31 16:46
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models

from internship.migrations.utils.groups import add_init_internship_manager_group, linkToDefaultCohort, \
    cleanupStudentInternshipsAndPersons
from internship.migrations.utils.uuid import set_uuid_field, set_uuid_field_2


class Migration(migrations.Migration):
    replaces = [
        ('internship', '0001_initial'),
        ('internship', '0002_internshipchoice'),
        ('internship', '0003_auto_20160527_1230'),
        ('internship', '0004_period'),
        ('internship', '0005_internshipoffer_selectable'),
        ('internship', '0006_auto_20160623_1647'),
        ('internship', '0007_auto_20160623_1633'),
        ('internship', '0008_internship_manager_permission'),
        ('internship', '0006_auto_20160627_1532'),
        ('internship', '0009_merge'),
        ('internship', '0010_remove_internshipenrollment_learning_unit_enrollment'),
        ('internship', '0011_auto_20160701_1700'),
        ('internship', '0012_auto_20160701_1712'),
        ('internship', '0013_create_internship_access_perm'),
        ('internship', '0014_add_and_init_groups'),
        ('internship', '0015_internshipspeciality'),
        ('internship', '0016_intenshipstudentinformations'),
        ('internship', '0017_auto_20160704_2259'),
        ('internship', '0018_internshipstudentaffectationstat'),
        ('internship', '0019_auto_20160715_1501'),
        ('internship', '0020_internshipspeciality_acronym'),
        ('internship', '0021_auto_20160817_1520'),
        ('internship', '0022_internshipchoice_internship_choice'),
        ('internship', '0023_internshipoffer_master'),
        ('internship', '0024_internshipspeciality_order_postion'),
        ('internship', '0025_affectationgenerationtime'),
        ('internship', '0026_internshipspecialitygroup_internshipspecialitygroupmember'),
        ('internship', '0027_add_uuid_field'),
        ('internship', '0028_populate_uuid_field'),
        ('internship', '0029_internshipstudentinformation_contest'),
        ('internship', '0030_auto_20170302_1133'),
        ('internship', '0031_add_uuid_field_period_places'),
        ('internship', '0032_populate_uuid_field_period_places'),
        ('internship', '0033_auto_20170308_1007'),
        ('internship', '0034_internshipenrollment_internship_choice'),
        ('internship', '0035_cohort_organization_period'),
        ('internship', '0036_cohort_internship_speciality'),
        ('internship', '0037_add_cohort_to_student_information'),
        ('internship', '0038_optimize_organization_address_queries'),
        ('internship', '0039_internship'),
        ('internship', '0040_auto_20170405_0942'),
        ('internship', '0041_internshipoffer_internship'),
        ('internship', '0042_internshipoffer_cohort'),
        ('internship', '0043_auto_20170405_2048'),
        ('internship', '0044_auto_20170406_1053'),
        ('internship', '0045_auto_20170407_1358'),
        ('internship', '0046_auto_20170410_1322'),
        ('internship', '0047_auto_20170410_1601'),
        ('internship', '0048_remove_old_choices_data'),
        ('internship', '0049_prevent_multiple_choices_for_preference'),
        ('internship', '0050_affectationgenerationtime_cohort')
    ]

    dependencies = [
        ('base', '0016_auto_20160224_1039'),
        ('base', '0035_auto_20160421_2347'),
        ('base', '0098_auto_20170306_0953'),
        ('contenttypes', '__latest__'),
        ('base', '0055_message_history_modifications'),
        ('base', '0058_add_initial_users_to_groups'),
        ('base', '0057_creation_and_initialisation_of_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=15)),
                ('website', models.URLField(blank=True, max_length=255, null=True)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('civility', models.CharField(blank=True, max_length=50, null=True)),
                ('type_mastery', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality', models.CharField(blank=True, max_length=50, null=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                                   to='internship.Organization')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('maximum_enrollments', models.IntegerField()),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
                ('selectable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='internship_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipOffer'),
        ),
        migrations.CreateModel(
            name='InternshipChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student')),
                ('priority', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PeriodInternshipPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_places', models.IntegerField(blank=None)),
                ('internship_offer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipOffer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Period')),
            ],
        ),
        migrations.AlterModelOptions(
            name='internshipoffer',
            options={'permissions': (
                ('is_internship_manager', 'Is Internship Manager'),
                ('can_access_internship', 'Can access internships'))},
        ),
        migrations.RemoveField(
            model_name='internshipenrollment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='internshipenrollment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.Period'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='place',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='internship.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='student',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.Student'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=add_init_internship_manager_group,
        ),
        migrations.CreateModel(
            name='InternshipSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('learning_unit',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnit')),
                ('mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='internshipchoice',
            name='speciality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='internship.InternshipSpeciality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='speciality',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='internship.InternshipSpeciality'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InternshipStudentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone_mobile', models.CharField(blank=True, max_length=100, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipStudentAffectationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(default='0', max_length=1)),
                ('cost', models.IntegerField()),
                ('consecutive_month', models.BooleanField(default=False)),
                ('organization',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Period')),
                ('speciality',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student')),
                ('type_of_internship', models.CharField(default='N', max_length=1)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipspeciality',
            name='acronym',
            field=models.CharField(default=' ', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, default='service partner', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internshipchoice',
            name='internship_choice',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='master',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='internshipspeciality',
            name='order_postion',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AffectationGenerationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('generated_by', models.CharField(default='None', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipSpecialityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipSpecialityGroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='internship.InternshipSpecialityGroup')),
                ('speciality',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality')),
            ],
        ),
        migrations.AddField(
            model_name='internshipchoice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='internshipspeciality',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='period',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(
            code=set_uuid_field,
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(choices=[('SP', 'SP'), ('SS', 'SS')], default='GENERALIST', max_length=124),
        ),
        migrations.AddField(
            model_name='periodinternshipplaces',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, null=True),
        ),
        migrations.RunPython(set_uuid_field_2
                             ),
        migrations.AlterField(
            model_name='periodinternshipplaces',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(choices=[('SPECIALIST', 'specialist'), ('GENERALIST', 'generalist')],
                                   default='GENERALIST', max_length=124),
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='internship_choice',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('free_internships_number', models.IntegerField()),
                ('publication_start_date', models.DateField()),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
        migrations.AddField(
            model_name='period',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
        migrations.AddField(
            model_name='internshipspeciality',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses',
                                    related_query_name='address', to='internship.Organization'),
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('length_in_periods', models.IntegerField(default=1)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort')),
                ('speciality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 to='internship.InternshipSpeciality')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='internshipchoice',
            old_name='internship_choice',
            new_name='internship',
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='internship',
            field=models.IntegerField(db_column='internship_choice'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Internship'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='internship.Internship'),
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.RunPython(
            code=linkToDefaultCohort,
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.RenameField(
            model_name='internshipenrollment',
            old_name='internship_choice',
            new_name='internship',
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='internship',
            field=models.IntegerField(db_column='internship_choice'),
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Internship'),
        ),
        migrations.RunSQL(
            sql="select setval('internship_internship_id_seq', 10);",
        ),
        migrations.AlterModelOptions(
            name='cohort',
            options={'ordering': ['name']},
        ),
        migrations.RunPython(
            code=cleanupStudentInternshipsAndPersons,
        ),
        migrations.AlterUniqueTogether(
            name='internshipchoice',
            unique_together={('student', 'internship', 'choice')},
        ),
        migrations.AddField(
            model_name='affectationgenerationtime',
            name='cohort',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='internship.Cohort'),
        ),
        migrations.RunSQL(
            sql='UPDATE internship_affectationgenerationtime SET cohort_id = (SELECT min(id) FROM internship_cohort)',
        ),
        migrations.AlterField(
            model_name='affectationgenerationtime',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
    ]
