# Generated by Django 3.2.21 on 2023-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', 'populate_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
