# Generated by Django 3.2.23 on 2023-12-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_alter_cohort_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_master',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
    ]
