# Generated by Django 2.2.13 on 2021-10-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_squashed_0107_internshipscore_student_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='student_affectation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='internship.InternshipStudentAffectationStat'),  # noqa
        ),
    ]
