# Generated by Django 2.2.13 on 2021-12-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_auto_20211026_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Organization'),  # noqa
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),  # noqa
        ),
    ]
