# Generated by Django 4.2.16 on 2024-09-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("internship", "0003_internshipmodalityapd"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="cohort",
            name="Une cohorte parente ne peut avoir des dates de publication et inscription",
        ),
        migrations.RemoveConstraint(
            model_name="cohort",
            name="Une sous-cohorte doit avoir des dates de publication et inscription",
        ),
        migrations.RemoveConstraint(
            model_name="cohort",
            name="Une cohorte parente ne peut avoir elle-même un parent",
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_parent", False),
                    ("publication_start_date__isnull", True),
                    _connector="OR",
                ),
                name="A parent cohort cannot have publication and subscription dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_parent", True),
                    ("publication_start_date__isnull", False),
                    _connector="OR",
                ),
                name="A subcohort must have publication and subscription dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_parent", False),
                    ("parent_cohort__isnull", True),
                    _connector="OR",
                ),
                name="A parent cohort cannot have a parent itself",
            ),
        ),
    ]
