# Generated by Django 2.2.13 on 2022-01-03 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_auto_20211214_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality')  # noqa,
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='acronym',
            field=models.CharField(blank=True, max_length=125, null=True),
        ),
    ]
