# Generated by Django 2.2.13 on 2022-01-10 17:03

import uuid

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import internship.models.enums.response_type


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_auto_20220103_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEvaluationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.IntegerField()),
                ('statement', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('C', 'Choice'), ('O', 'Open')], default=internship.models.enums.response_type.ResponseType('Open'), max_length=10)),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
