# Generated by Django 2.2.13 on 2022-01-20 11:23

import uuid

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_auto_20220103_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEvaluationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order', models.IntegerField()),
                ('statement', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('CHOICE', 'Choice'), ('OPEN', 'Open')], default='Open', max_length=10)),  # noqa
                ('options', django.contrib.postgres.fields.jsonb.JSONField(default=list)),
                ('active', models.BooleanField(default=True)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort')),  # noqa
            ],
            options={
                'unique_together': {('cohort', 'order')},
            },
        ),
    ]
