# Generated by Django 4.2.16 on 2024-12-03 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0707_django_4_migration'),
        ('reference', '0018_country_active'),
        ('internship', '0004_remove_organization_report_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationgenerationtime',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='affectationgenerationtime',
            name='end_date_time',
            field=models.DateTimeField(verbose_name='End date time'),
        ),
        migrations.AlterField(
            model_name='affectationgenerationtime',
            name='generated_by',
            field=models.CharField(default='None', max_length=255, verbose_name='Generated by'),
        ),
        migrations.AlterField(
            model_name='affectationgenerationtime',
            name='start_date_time',
            field=models.DateTimeField(verbose_name='Start date time'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='is_parent',
            field=models.BooleanField(default=False, verbose_name='Is parent'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='originated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Originated from'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='parent_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcohorts', to='internship.cohort', verbose_name='Parent cohort'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='publication_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publication start date'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='subscription_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription end date'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription start date'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='length_in_periods',
            field=models.IntegerField(default=1, verbose_name='Length in periods'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='position',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipspeciality', verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='internshipcertifier',
            name='civility',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'PROFESSOR'), ('DOCTOR', 'DOCTOR')], max_length=50, null=True, verbose_name='Civility'),
        ),
        migrations.AlterField(
            model_name='internshipcertifier',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='internshipcertifier',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='internshipcertifier',
            name='signature_b64',
            field=models.TextField(blank=True, null=True, verbose_name='Signature'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='choice',
            field=models.IntegerField(verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internship', verbose_name='Internship'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='priority',
            field=models.BooleanField(verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='registered',
            field=models.DateTimeField(null=True, verbose_name='Registered'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipspeciality', verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='internshipchoice',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internship', verbose_name='Internship'),
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='internship_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internshipoffer', verbose_name='Internship Offer'),
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.organization', verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='internshipenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='civility',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'PROFESSOR'), ('DOCTOR', 'DOCTOR')], max_length=50, null=True, verbose_name='Civility'),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='start_activities',
            field=models.DateField(blank=True, null=True, verbose_name='Start activities'),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='user_account_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='User account expiration date'),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='user_account_status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE')], default='INACTIVE', max_length=50, verbose_name='User account status'),
        ),
        migrations.AlterField(
            model_name='internshipmodalityapd',
            name='apd',
            field=models.IntegerField(verbose_name='APD'),
        ),
        migrations.AlterField(
            model_name='internshipmodalityapd',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.internship', verbose_name='Internship'),
        ),
        migrations.AlterField(
            model_name='internshipmodalityperiod',
            name='internship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.internship', verbose_name='Internship'),
        ),
        migrations.AlterField(
            model_name='internshipmodalityperiod',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='master',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='maximum_enrollments',
            field=models.IntegerField(verbose_name='Maximum enrollments'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='selectable',
            field=models.BooleanField(default=True, verbose_name='Selectable'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipspeciality', verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='comments',
            field=models.JSONField(blank=True, default=dict, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='excused',
            field=models.BooleanField(default=False, verbose_name='Excused'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='objectives',
            field=models.JSONField(blank=True, default=dict, verbose_name='Objectives'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='student_affectation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='internship.internshipstudentaffectationstat', verbose_name='Student Affectation'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='student_presence',
            field=models.BooleanField(null=True, verbose_name='Student presence'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validated'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.person', verbose_name='Validated by'),
        ),
        migrations.AlterField(
            model_name='internshipscoremapping',
            name='apd',
            field=models.IntegerField(verbose_name='APD'),
        ),
        migrations.AlterField(
            model_name='internshipscoremapping',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='internshipscoremapping',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='internshipscorereason',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='acronym',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='mandatory',
            field=models.BooleanField(default=False, verbose_name='Mandatory'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipspeciality', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='selectable',
            field=models.BooleanField(default=True, verbose_name='Selectable'),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='sequence',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='choice',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('E', 'E'), ('I', 'I'), ('X', 'X')], default='0', max_length=1, verbose_name='Choice'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='consecutive_month',
            field=models.BooleanField(default=False, verbose_name='Consecutive month'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='cost',
            field=models.IntegerField(verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internship', verbose_name='Internship'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='internship_evaluated',
            field=models.BooleanField(default=False, verbose_name='Internship evaluated'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipspeciality', verbose_name='Speciality'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='type',
            field=models.CharField(choices=[('S', 'S'), ('N', 'N'), ('X', 'X')], default='N', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='city',
            field=models.CharField(max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'Specialist'), ('GENERALIST', 'Generalist')], max_length=124, null=True, verbose_name='Contest'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='country',
            field=models.CharField(max_length=255, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='evolution_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Evolution Score'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='evolution_score_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Evolution Score Reason'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='postal_code',
            field=models.CharField(max_length=20, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='masterallocation',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internshipmaster', verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='masterallocation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='masterallocation',
            name='role',
            field=models.CharField(choices=[('MASTER', 'MASTER'), ('DELEGATE', 'DELEGATE')], default='MASTER', max_length=50, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='masterallocation',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipspeciality', verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, max_length=15, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='fake',
            field=models.BooleanField(default=False, verbose_name='Fake'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='reference',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Reference'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_address',
            field=models.IntegerField(blank=True, default=11, null=True, verbose_name='Report address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_birthdate',
            field=models.IntegerField(blank=True, default=7, null=True, verbose_name='Report birthdate'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_city',
            field=models.IntegerField(blank=True, default=13, null=True, verbose_name='Report city'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_email',
            field=models.IntegerField(blank=True, default=8, null=True, verbose_name='Report email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_end_date',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Report end date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_first_name',
            field=models.IntegerField(blank=True, default=5, null=True, verbose_name='Report first name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_last_name',
            field=models.IntegerField(blank=True, default=4, null=True, verbose_name='Report last name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_master',
            field=models.IntegerField(blank=True, default=14, null=True, verbose_name='Report master'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_noma',
            field=models.IntegerField(blank=True, default=9, null=True, verbose_name='Report noma'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_period',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Report period'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_phone',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Report phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_postal_code',
            field=models.IntegerField(blank=True, default=12, null=True, verbose_name='Report postal code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_specialty',
            field=models.IntegerField(blank=True, default=6, null=True, verbose_name='Report specialty'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='report_start_date',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Report start date'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_end',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='date_start',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='period',
            name='exclude_from_assignment',
            field=models.BooleanField(default=False, verbose_name='Exclude from assignment'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='period',
            name='remedial',
            field=models.BooleanField(default=False, verbose_name='Remedial'),
        ),
        migrations.AlterField(
            model_name='periodinternshipplaces',
            name='internship_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.internshipoffer', verbose_name='Internship Offer'),
        ),
        migrations.AlterField(
            model_name='periodinternshipplaces',
            name='number_places',
            field=models.IntegerField(verbose_name='Number places'),
        ),
        migrations.AlterField(
            model_name='periodinternshipplaces',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.period', verbose_name='Period'),
        ),
        migrations.AlterField(
            model_name='placeevaluation',
            name='affectation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipstudentaffectationstat', verbose_name='Affectation'),
        ),
        migrations.AlterField(
            model_name='placeevaluation',
            name='evaluation',
            field=models.JSONField(null=True, verbose_name='Evaluation'),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.cohort', verbose_name='Cohort'),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='options',
            field=models.JSONField(default=list, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Required'),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='statement',
            field=models.CharField(max_length=300, verbose_name='Statement'),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('OPEN', 'Open'), ('NUMBER', 'Number')], default='Open', max_length=10, verbose_name='Type'),
        ),
    ]
