# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0004_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='selectable',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
