# Generated by Django 4.2.16 on 2025-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0708_educationgroupyear_type_de_ponderation'),
        ('internship', '0005_alter_affectationgenerationtime_cohort_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='is_preconcours',
            field=models.BooleanField(default=False, verbose_name='Preconcours'),
        ),
    ]
