# Generated by Django 2.2.13 on 2022-01-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_placeevaluationitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeevaluationitem',
            options={'ordering': ('order',)},
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='placeevaluationitem',
            unique_together=set(),
        ),
    ]
