# Generated by Django 2.2.13 on 2022-01-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_placeevaluationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('OPEN', 'Open')], default='OPEN', max_length=10),
        ),
    ]
