# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_auto_20160623_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodInternshipPlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_places', models.IntegerField(blank=None)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipOffer')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Period')),
            ],
        ),
    ]
