# Generated by Django 3.2.12 on 2022-02-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('internship', '0006_auto_20220120_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='comments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='objectives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='student_presence',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
