# Generated by Django 2.2.13 on 2022-01-10 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_auto_20220110_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeevaluationitem',
            name='cohort',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
    ]
