# Generated by Django 4.2.16 on 2025-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_add_preconcours_flag_to_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='behavior_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Behavior score'),
        ),
        migrations.AddField(
            model_name='internshipscore',
            name='competency_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Competency score'),
        ),
    ]
