# Generated by Django 3.2.12 on 2022-03-31 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_period_remedial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='comments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='objectives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='student_presence',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
