# Generated by Django 4.2.16 on 2025-03-04 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0007_internshipscore_behavior_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='behavior_score',
            field=models.IntegerField(
                blank=True, null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)],
                verbose_name='Behavior score'
            ),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='competency_score',
            field=models.IntegerField(
                blank=True, null=True,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)],
                verbose_name='Skill score'
            ),
        ),
        migrations.AlterField(
            model_name='period',
            name='is_preconcours',
            field=models.BooleanField(default=False, verbose_name='Pre-concours'),
        ),
    ]
