# Generated by Django 2.2.24 on 2022-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0008_auto_20220401_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
