# Generated by Django 3.2.12 on 2022-04-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_auto_20220404_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
