# Generated by Django 4.2.20 on 2025-04-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_internshipscore_preconcours_evaluation_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='date_end',
            field=models.DateField(blank=True, null=True, verbose_name='Effective end date'),
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='date_start',
            field=models.DateField(blank=True, null=True, verbose_name='Effective start date'),
        ),
    ]
