# Generated by Django 4.2.20 on 2025-06-05 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0010_internshipstudentaffectationstat_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='behavior_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Behavior score'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='competency_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Skill score'),
        ),
    ]
