# Generated by Django 3.2.12 on 2022-04-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_auto_20220411_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='order',
            field=models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order'),
        ),
    ]
