# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0012_auto_20160701_1712'),
        ('base','0057_creation_and_initialisation_of_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipoffer',
            options={'permissions': (('is_internship_manager', 'Is Internship Manager'), ('can_access_internship', 'Can access internships'))},
        ),
    ]