# Generated by Django 3.2.12 on 2022-04-25 14:58

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunPython

from internship.models.enums.role import Role


def default_validated_by_to_internship_master(apps, schema_editor):
    InternshipScore = apps.get_model('internship', 'InternshipScore')
    MasterAllocation = apps.get_model('internship', 'MasterAllocation')

    for internship_score in InternshipScore.objects.filter(
        student_affectation__isnull=False, validated_by__isnull=True
    ):
        allocation = MasterAllocation.objects.filter(
            organization=internship_score.student_affectation.organization,
            specialty=internship_score.student_affectation.speciality,
            role=Role.MASTER.name,
        ).first()
        if allocation:
            internship_score.validated_by = allocation.master
            internship_score.save()


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0013_internshipmaster_user_account_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipmaster'),  # noqa: E501
        ),
        migrations.RunPython(default_validated_by_to_internship_master, RunPython.noop, elidable=True),
    ]
