# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 09:54
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0014_add_and_init_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('learning_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnit')),
            ],
        ),
        migrations.AddField(
            model_name='internshipspeciality',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='name',
            field=models.CharField(max_length=125),
        ),
        migrations.RemoveField(
            model_name='internshipchoice',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='learning_unit_year',
        ),
        migrations.AddField(
            model_name='internshipchoice',
            name='speciality',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='speciality',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
            preserve_default=False,
        ),
    ]
