# Generated by Django 3.2.12 on 2022-04-28 11:41

import django.db.models.deletion
from django.db import migrations, models
from django.db.migrations import RunPython


def default_validated_by_to_internship_master_person(apps, schema_editor):
    InternshipScore = apps.get_model('internship', 'InternshipScore')
    InternshipMaster = apps.get_model('internship', 'InternshipMaster')

    for internship_score in InternshipScore.objects.filter(
        student_affectation__isnull=False,
        validated_by__isnull=False,
    ):
        master = InternshipMaster.objects.get(id=internship_score.validated_by_id)
        internship_score.validated_by_id = master.person_id
        internship_score.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0628_auto_20220401_1422'),
        ('internship', '0014_internshipscore_validated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.person'),  # noqa: E501
        ),
        migrations.RunPython(default_validated_by_to_internship_master_person, RunPython.noop, elidable=True),
    ]
