# Generated by Django 3.2.12 on 2022-04-29 15:36
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_alter_internshipscore_validated_by'),
    ]

    operations = []
