# Generated by Django 3.2.12 on 2022-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0017_retrieve_user_account_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='fake',
            field=models.BooleanField(default=False),
        ),
    ]
