# Generated by Django 3.2.16 on 2022-11-30 14:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0641_alter_programmanager_cohort'),
        ('internship', '0018_organization_fake'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipCertifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('civility', models.CharField(blank=True, choices=[('PROFESSOR', 'PROFESSOR'), ('DOCTOR', 'DOCTOR')], max_length=50, null=True)),  # noqa
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_b64', models.BinaryField(blank=True, null=True)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.person')),  # noqa
            ],
            options={
                'abstract': False,
            },
        ),
    ]
