# Generated by Django 3.2.16 on 2022-12-15 13:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0020_alter_internshipcertifier_signature_b64'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('evaluation', models.JSONField()),
                ('affectation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.internshipstudentaffectationstat')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
