# Generated by Django 3.2.16 on 2022-12-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_placeevaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeevaluation',
            options={},
        ),
        migrations.RemoveField(
            model_name='placeevaluation',
            name='order',
        ),
        migrations.AlterField(
            model_name='placeevaluation',
            name='evaluation',
            field=models.JSONField(null=True),
        ),
    ]
