# Generated by Django 3.2.16 on 2022-12-16 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_auto_20221216_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeevaluation',
            name='uuid',
        ),
    ]
