# Generated by Django 3.2.16 on 2022-12-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0023_remove_placeevaluation_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='type',
            field=models.CharField(choices=[('CHOICE', 'Choice'), ('OPEN', 'Open'), ('NUMBER', 'Number')],
                                   default='Open', max_length=10),
        ),
    ]
