# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0023_internshipoffer_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='order_postion',
            field=models.IntegerField(default=0),
        ),
    ]
