# Generated by Django 3.2.16 on 2023-01-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_alter_placeevaluationitem_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='placeevaluationitem',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
