# Generated by Django 3.2.16 on 2023-01-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0026_period_place_evaluation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='comments',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='objectives',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='placeevaluationitem',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
