# Generated by Django 3.2.18 on 2023-09-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0028_auto_20230920_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='is_parent',
            field=models.BooleanField(default=False),
        ),
    ]
