# Generated by Django 3.2.18 on 2023-09-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0029_cohort_is_parent'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(
                check=models.Q(('is_parent', False), ('publication_start_date__isnull', True), _connector='OR'),
                name='A parent cohort cannot have publication and subscription dates'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(
                check=models.Q(('is_parent', True), ('publication_start_date__isnull', False), _connector='OR'),
                name='A subcohort must have publication and subscription dates'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(
                check=models.Q(('is_parent', False), ('parent_cohort__isnull', True), _connector='OR'),
                name='A parent cohort cannot have a parent itself'),
        ),
    ]
