# Generated by Django 3.2.18 on 2023-09-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_internshipmodalityperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='exclude_from_assignment',
            field=models.BooleanField(default=False),
        ),
    ]
