# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0032_populate_uuid_field_period_places'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(choices=[('SPECIALIST', 'specialist'), ('GENERALIST', 'generalist')], default='GENERALIST', max_length=124),
        ),
    ]
