# Generated by Django 3.2.18 on 2023-10-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0033_period_exclude_from_assignment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cohort',
            name='A parent cohort cannot have publication and subscription dates',
        ),
        migrations.RemoveConstraint(
            model_name='cohort',
            name='A subcohort must have publication and subscription dates',
        ),
        migrations.RemoveConstraint(
            model_name='cohort',
            name='A parent cohort cannot have a parent itself',
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(check=models.Q(('is_parent', False), ('publication_start_date__isnull', True), _connector='OR'), name='Une cohorte parente ne peut avoir des dates de publication et inscription'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(check=models.Q(('is_parent', True), ('publication_start_date__isnull', False), _connector='OR'), name='Une sous-cohorte doit avoir des dates de publication et inscription'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(check=models.Q(('is_parent', False), ('parent_cohort__isnull', True), _connector='OR'), name='Une cohorte parente ne peut avoir elle-même un parent'),
        ),
    ]
