# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 12:32
from __future__ import unicode_literals

import uuid

import django.db.models.deletion
from django.db import migrations, models

from osis_common.models.serializable_model import SerializableModel
from internship.models.cohort import Cohort
from internship.models.organization import Organization
from internship.models.period import Period


def create_the_first_cohort(apps, schema_editor):
    cohort = Cohort(name='M7-2018',
                    uuid="1091eebf-e3ed-4cfd-b13e-6b9e947f14bb",
                    description='M7-2018',
                    free_internships_number=8,
                    publication_start_date="2017-03-27",
                    subscription_start_date="2017-03-01",
                    subscription_end_date="2017-03-20")
    super(SerializableModel, cohort).save() # Avoids passing through the queue


def assign_first_cohort_to_periods_and_organizations(apps, schema_editor):
    cohort = Cohort.objects.first()
    Period.objects.all().update(cohort=cohort)
    Organization.objects.all().update(cohort=cohort)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20170306_0953'),
        ('internship', '0034_internshipenrollment_internship_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('free_internships_number', models.IntegerField()),
                ('publication_start_date', models.DateField()),
                ('subscription_start_date', models.DateField()),
                ('subscription_end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='cohort',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='period',
            name='cohort',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.RunPython(create_the_first_cohort),
        migrations.RunPython(assign_first_cohort_to_periods_and_organizations),
        migrations.AlterField(
            model_name="organization",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="period",
            name="cohort",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
    ]
