# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-03 11:46
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0035_cohort_organization_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='cohort',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
    ]
