# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 14:01
from __future__ import unicode_literals

from django.db import migrations

from internship.migrations.utils.groups import cleanupStudentInternshipsAndPersons


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0046_auto_20170410_1322'),
    ]

    operations = [
        migrations.RunPython(cleanupStudentInternshipsAndPersons, elidable=True)
    ]
