# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0047_auto_20170410_1601'),
    ]

    operations = []
