# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-17 21:12
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0049_prevent_multiple_choices_for_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationgenerationtime',
            name='cohort',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
        migrations.RunSQL("UPDATE internship_affectationgenerationtime SET cohort_id = (SELECT min(id) FROM internship_cohort)", elidable=True),
        migrations.AlterField(
            model_name='affectationgenerationtime',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        )
    ]
