# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0053_remove_internshipoffer_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipspeciality',
            name='order_position',
        ),
        migrations.AddField(
            model_name='internship',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
