# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0054_auto_20170804_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipspecialitygroupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='internshipspecialitygroupmember',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='internshipspeciality',
            name='order_position',
        ),
        migrations.AddField(
            model_name='internshipspeciality',
            name='sequence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='InternshipSpecialityGroup',
        ),
        migrations.DeleteModel(
            name='InternshipSpecialityGroupMember',
        ),
    ]
