# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0055_auto_20171120_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='report_address',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_birthdate',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_city',
            field=models.IntegerField(blank=True, default=14, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_email',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_end_date',
            field=models.IntegerField(blank=True, default=3, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_first_name',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_gender',
            field=models.IntegerField(blank=True, default=6, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_last_name',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_noma',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_period',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_phone',
            field=models.IntegerField(blank=True, default=11, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_postal_code',
            field=models.IntegerField(blank=True, default=13, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_specialty',
            field=models.IntegerField(blank=True, default=7, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='report_start_date',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
