# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0016_auto_20170410_1318'),
        ('internship', '0056_auto_20171129_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='speciality',
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='email_private',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='phone_mobile',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='start_activities',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='civility',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'Professor'), ('DOCTOR', 'Doctor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='type_mastery',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'Specialist'), ('GENERALIST', 'Generalist')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='masterallocation',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipMaster'),
        ),
        migrations.AddField(
            model_name='masterallocation',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Organization'),
        ),
        migrations.AddField(
            model_name='masterallocation',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
        ),
    ]
