# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0058_internshipmaster_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='civility',
            field=models.CharField(blank=True, choices=[('PROFESSOR', 'PROFESSOR'), ('DOCTOR', 'DOCTOR')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEMALE', 'F'), ('MALE', 'M')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='type_mastery',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'SPECIALIST'), ('GENERALIST', 'GENERALIST')], max_length=50, null=True),
        ),
    ]
