# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0059_auto_20171220_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaddress',
            name='ignore',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('M', 'M')], max_length=1, null=True),
        ),
    ]
