# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0060_auto_20180108_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationaddress',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.DeleteModel(
            name='OrganizationAddress',
        ),
    ]
