# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0061_auto_20180112_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipspeciality',
            name='learning_unit',
        ),
    ]
