# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 14:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0062_remove_internshipspeciality_learning_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='longitude',
        ),
    ]
