# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 16:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0063_auto_20180116_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='originated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
        ),
    ]
