# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0064_cohort_originated_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='alternate_speciality',
        ),
    ]
