# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0065_remove_internship_alternate_speciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipchoice',
            name='registered',
            field=models.DateTimeField(null=True),
        ),
    ]
