# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0066_internshipchoice_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='selectable',
            field=models.BooleanField(default=True),
        ),
    ]
