# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0067_internshipspeciality_selectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(choices=[('SPECIALIST', 'specialist'), ('GENERALIST', 'generalist')], max_length=124, null=True),
        ),
    ]
