# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-06 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0069_auto_20180202_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipmaster',
            name='type_mastery',
        ),
    ]
