# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-20 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0070_remove_internshipmaster_type_mastery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='choice',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('E', 'E'), ('I', 'I'), ('X', 'X')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='type_of_internship',
            field=models.CharField(choices=[('S', 'S'), ('N', 'N'), ('X', 'X')], default='N', max_length=1),
        ),
    ]
