# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-13 14:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0071_auto_20180220_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipstudentaffectationstat',
            old_name='type_of_internship',
            new_name='type',
        ),
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='internship.Internship'),
        ),
        migrations.AlterField(
            model_name='periodinternshipplaces',
            name='number_places',
            field=models.IntegerField(),
        ),
    ]
