# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-04 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0072_auto_20180313_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='last_name',
            field=models.CharField(db_index=True, default='ANONYMOUS', max_length=50),
            preserve_default=False,
        ),
    ]
