# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0073_auto_20180504_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male')], max_length=1, null=True),
        ),
    ]
