# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-08-10 12:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0074_auto_20180629_1108'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('cohort', 'reference')]),
        ),
    ]
