# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-22 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0075_auto_20180810_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='contest',
            field=models.CharField(blank=True, choices=[('SPECIALIST', 'Specialist'), ('GENERALIST', 'Generalist')], max_length=124, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together=set([('reference', 'cohort')]),
        ),
    ]
