# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-07 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0076_auto_20181122_1310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipspeciality',
            options={'ordering': ('name',)},
        ),
    ]
