# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-02-22 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0077_auto_20190208_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipchoice',
            name='priority',
            field=models.BooleanField(),
        ),
    ]
