# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0079_internshipscore_internshipscoremapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
