# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-07-24 11:07
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0080_internshipscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.Cohort'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.Period'),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Student'),
        ),
        migrations.AlterField(
            model_name='internshipscoremapping',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.Cohort'),
        ),
        migrations.AlterField(
            model_name='internshipscoremapping',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='internship.Period'),
        ),
    ]
