# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-05 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0082_internshipstudentaffectationstat_internship_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='evolution_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
