# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-08-21 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0083_internshipstudentinformation_evolution_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='email_private',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Private email'),
        ),
    ]
