# Generated by Django 2.2.10 on 2020-06-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0087_internshipscorereason'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
