# Generated by Django 2.2.10 on 2020-06-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0088_internshipscore_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='evolution_score_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
