# Generated by Django 3.1.1 on 2020-11-27 11:19

import uuid
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    MasterAllocation = apps.get_model('internship', 'MasterAllocation')
    for allocation in MasterAllocation.objects.all():
        allocation.uuid = uuid.uuid4()
        allocation.save()


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0089_internshipstudentinformation_evolution_score_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterallocation',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='masterallocation',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
        )
    ]
