# Generated by Django 3.1.1 on 2020-11-30 16:17
import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.migrations import RunPython


def create_persons(apps, schema_editor):
    InternshipMaster = apps.get_model('internship', 'InternshipMaster')
    Person = apps.get_model('base', 'Person')
    for master in InternshipMaster.objects.all():
        email = master.email or master.email_private
        if email and not master.person:
            person_instance = Person.objects.create(
                uuid=uuid.uuid4(),
                last_name=master.last_name,
                first_name=master.first_name,
                gender=master.gender,
                email=email,
                phone=master.phone,
                phone_mobile=master.phone_mobile,
                birth_date=master.birth_date
            )
            master.person = person_instance
            master.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0543_auto_20201120_1040'),
        ('internship', '0092_clean_master_duplicates'),
    ]

    operations = [
        # link to person fk
        migrations.AddField(
            model_name='internshipmaster',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='base.person'),
        ),
        # create persons based on data
        migrations.RunPython(create_persons, RunPython.noop),
        # remove fields that are available in Person table
        migrations.RemoveField(
            model_name='internshipmaster',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='email',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='phone_mobile',
        ),
    ]
