# Generated by Django 3.1.1 on 2020-12-14 16:37

from django.db import migrations
from django.db.migrations import RunPython
from django.db.models import Q


def move_master_address_to_person_address(apps, schema_editor):
    InternshipMaster = apps.get_model('internship', 'InternshipMaster')
    PersonAddress = apps.get_model('base', 'PersonAddress')
    Country = apps.get_model('reference', 'Country')

    default_country = Country.objects.filter(iso_code='BE').first()

    # create person address only if record has at least one of the following column not null
    for master in InternshipMaster.objects.filter(
        Q(location__isnull=False) | Q(postal_code__isnull=False) | Q(city__isnull=False) | Q(country__isnull=False)
    ):
        if master.person and not PersonAddress.objects.filter(person=master.person).exists():
            PersonAddress.objects.create(
                person=master.person,
                location=master.location,
                postal_code=master.postal_code,
                city=master.city,
                country=master.country or default_country
            )


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0093_internshipmaster_person'),
    ]

    operations = [
        migrations.RunPython(move_master_address_to_person_address, RunPython.noop, elidable=True),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='city',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='country',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='location',
        ),
        migrations.RemoveField(
            model_name='internshipmaster',
            name='postal_code',
        ),
    ]
