# Generated by Django 3.1.1 on 2021-01-21 16:18
from django.contrib.postgres.fields import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0095_internshipmaster_user_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='comments',
            field=JSONField(blank=True, null=True),
        ),
    ]
