# Generated by Django 3.1.1 on 2021-01-21 16:50
from django.contrib.postgres.fields import JSONField
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0096_internshipscore_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='objectives',
            field=JSONField(default=dict),
        ),
    ]
