# Generated by Django 3.1.1 on 2021-02-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0097_internshipscore_objectives'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipmaster',
            name='role',
            field=models.CharField(choices=[('MASTER', 'Master'), ('DELEGATE', 'Delegate')], default='MASTER', max_length=50),
        ),
    ]
