# Generated by Django 3.1.1 on 2021-02-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0098_internshipmaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='role',
            field=models.CharField(choices=[('MASTER', 'MASTER'), ('DELEGATE', 'DELEGATE')], default='MASTER', max_length=50),
        ),
    ]
