# Generated by Django 3.1.1 on 2021-02-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0568_auto_20210224_1542'),
        ('internship', '0099_period_sent_reminder_mail'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internshipscore',
            unique_together={('student', 'period')},
        ),
    ]
