# Generated by Django 3.1.1 on 2021-03-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0101_internshipscore_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipmaster',
            name='role',
        ),
        migrations.AddField(
            model_name='masterallocation',
            name='role',
            field=models.CharField(choices=[('MASTER', 'MASTER'), ('DELEGATE', 'DELEGATE')], default='MASTER', max_length=50),
        ),
    ]
