# Generated by Django 3.1.1 on 2021-03-16 16:28

from django.db import migrations, models
import django.db.models.deletion
from django.db.migrations import RunPython


def link_scores_with_affectations(apps, schema_editor):
    InternshipScore = apps.get_model('internship', 'InternshipScore')
    InternshipStudentAffectationStat = apps.get_model('internship', 'InternshipStudentAffectationStat')

    scores = InternshipScore.objects.all()
    students = scores.values('student_id')
    affectations = InternshipStudentAffectationStat.objects.filter(student_id__in=students)

    for score in scores:
        for affectation in affectations:
            if score.student_id == affectation.student_id and score.period_id == affectation.period_id:
                score.student_affectation = affectation
                score.save()
                break


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0102_auto_20210310_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='student_affectation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='score', to='internship.internshipstudentaffectationstat'),
        ),
        migrations.RunPython(link_scores_with_affectations, reverse_code=RunPython.noop)
    ]
