# Generated by Django 3.1.1 on 2021-03-23 15:49

from django.db import migrations, models
from django.db.migrations import RunPython
from django.db.models import F
from django.db.models.functions import Upper


def convert_status_values_to_upper(apps, schema_editor):
    InternshipMaster = apps.get_model('internship', 'InternshipMaster')
    InternshipMaster.objects.all().update(user_account_status=Upper(F('user_account_status')))


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0103_internshipscore_student_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='user_account_status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE')], default='INACTIVE', max_length=50),
        ),
        migrations.RunPython(convert_status_values_to_upper, reverse_code=RunPython.noop, elidable=True)
    ]
