# Generated by Django 3.1.1 on 2021-03-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0103_internshipscore_student_affectation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='user_account_status',
            field=models.CharField(choices=[('INACTIVE', 'INACTIVE'), ('PENDING', 'PENDING'), ('ACTIVE', 'ACTIVE')], default='INACTIVE', max_length=50),
        ),
    ]
