# Generated by Django 3.1.1 on 2021-04-06 14:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0105_auto_20210323_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipscore',
            name='comments',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='internshipscore',
            name='objectives',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
