# Generated by Django 3.1.1 on 2021-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0106_auto_20210406_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipscore',
            name='student_presence',
            field=models.NullBooleanField(),
        ),
    ]
