# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0035_auto_20160421_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to Director'), ('DIR_OK', 'Accepted by Director'), ('DIR_KO', 'Refused by Director'), ('COM_SUBMIT', 'Submitted to Commission'), ('COM_OK', 'Accepted by Commission'), ('COM_KO', 'Refused by Commission'), ('EVA_SUBMIT', 'Submitted to First Year Evaluation'), ('EVA_OK', 'Accepted by First Year Evaluation'), ('EVA_KO', 'Refused by First Year Evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended')], default='DRAFT', max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear')),
                ('learning_unit_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitEnrollment')),
            ],
        ),
        migrations.CreateModel(
            name='DissertationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
            ],
        ),
        migrations.CreateModel(
            name='DissertationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAdviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='OfferProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('offer_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear')),
            ],
        ),
        migrations.CreateModel(
            name='PropositionDissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration', models.CharField(choices=[('POSSIBLE', 'Possible'), ('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden')], default='FORBIDDEN', max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('DOMAIN', 'Domain'), ('WORK', 'Work'), ('QUESTION', 'Question'), ('THEME', 'Theme')], default='DOMAIN', max_length=12)),
                ('max_number_student', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('RDL', 'Litterature review'), ('EDC', 'Case study')], default='RDL', max_length=12)),
                ('visibility', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
        migrations.CreateModel(
            name='PropositionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('proposition_dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation')),
            ],
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation'),
        ),
        migrations.AddField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation'),
        ),
    ]
