# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0054_scoresencoding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRF', 'Professor'), ('MGR', 'Manager')], default='PRF', max_length=3)),
                ('available_by_email', models.BooleanField(default=False)),
                ('available_by_phone', models.BooleanField(default=False)),
                ('available_at_office', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, default='')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
            options={
                'ordering': ['person__last_name', 'person__middle_name', 'person__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Dissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to Director'), ('DIR_OK', 'Accepted by Director'), ('DIR_KO', 'Refused by Director'), ('COM_SUBMIT', 'Submitted to Commission'), ('COM_OK', 'Accepted by Commission'), ('COM_KO', 'Refused by Commission'), ('EVA_SUBMIT', 'Submitted to First Year Evaluation'), ('EVA_OK', 'Accepted by First Year Evaluation'), ('EVA_KO', 'Refused by First Year Evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended'), ('ENDED_WIN', 'Ended Win'), ('ENDED_LOS', 'Ended Los')], default='DRAFT', max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student')),
                ('offer_year_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear')),
            ],
            options={
                'ordering': ['author__person__last_name', 'author__person__middle_name', 'author__person__first_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DissertationGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
            ],
        ),
        migrations.CreateModel(
            name='DissertationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROMOTEUR', 'Pro'), ('CO_PROMOTEUR', 'CoPro'), ('READER', 'Reader')], max_length=12)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAdviser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='OfferProposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=200)),
                ('student_can_manage_readers', models.BooleanField(default=True)),
                ('readers_visibility_date_for_students', models.BooleanField(default=False)),
                ('adviser_can_suggest_reader', models.BooleanField(default=False)),
                ('evaluation_first_year', models.BooleanField(default=False)),
                ('validation_commission_exists', models.BooleanField(default=False)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='PropositionDissertation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaboration', models.CharField(choices=[('POSSIBLE', 'Possible'), ('REQUIRED', 'Required'), ('FORBIDDEN', 'Forbidden')], default='FORBIDDEN', max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('DOMAIN', 'Domain'), ('WORK', 'Work'), ('QUESTION', 'Question'), ('THEME', 'Theme')], default='DOMAIN', max_length=12)),
                ('max_number_student', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('RDL', 'Litterature review'), ('EDC', 'Case study')], default='RDL', max_length=12)),
                ('visibility', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('offer_proposition', models.ManyToManyField(to='dissertation.OfferProposition')),
            ],
            options={
                'ordering': ['author__person__last_name', 'author__person__middle_name', 'author__person__first_name', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PropositionRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser')),
                ('proposition_dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation')),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='proposition_dissertation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation'),
        ),
    ]
