# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20160623_1006'),
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DissertationUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_from', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to Director'), ('DIR_OK', 'Accepted by Director'), ('DIR_KO', 'Refused by Director'), ('COM_SUBMIT', 'Submitted to Commission'), ('COM_OK', 'Accepted by Commission'), ('COM_KO', 'Refused by Commission'), ('EVA_SUBMIT', 'Submitted to First Year Evaluation'), ('EVA_OK', 'Accepted by First Year Evaluation'), ('EVA_KO', 'Refused by First Year Evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended'), ('ENDED_WIN', 'Ended Win'), ('ENDED_LOS', 'Ended Los')], default='DRAFT', max_length=12)),
                ('status_to', models.CharField(choices=[('DRAFT', 'Draft'), ('DIR_SUBMIT', 'Submitted to Director'), ('DIR_OK', 'Accepted by Director'), ('DIR_KO', 'Refused by Director'), ('COM_SUBMIT', 'Submitted to Commission'), ('COM_OK', 'Accepted by Commission'), ('COM_KO', 'Refused by Commission'), ('EVA_SUBMIT', 'Submitted to First Year Evaluation'), ('EVA_OK', 'Accepted by First Year Evaluation'), ('EVA_KO', 'Refused by First Year Evaluation'), ('TO_RECEIVE', 'To be received'), ('TO_DEFEND', 'To be defended'), ('DEFENDED', 'Defended'), ('ENDED', 'Ended'), ('ENDED_WIN', 'Ended Win'), ('ENDED_LOS', 'Ended Los')], default='DRAFT', max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('justification', models.TextField(default=' ')),
                ('dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='day_of_month_end_visibility_dissertation',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='day_of_month_end_visibility_proposition',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='day_of_month_start_visibility_dissertation',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='day_of_month_start_visibility_proposition',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='month_end_visibility_dissertation',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='month_end_visibility_proposition',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='month_start_visibility_dissertation',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='month_start_visibility_proposition',
            field=models.IntegerField(default=9),
        ),
    ]
