# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositiondissertation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser'),
        ),
    ]
