# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0002_auto_20160425_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='email_accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adviser',
            name='phone_accept',
            field=models.BooleanField(default=False),
        ),
    ]
