# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0003_auto_20160426_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='office_accept',
            field=models.BooleanField(default=False),
        ),
    ]
