# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0004_adviser_office_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
