# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-28 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0004_auto_20160628_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propositionrole',
            name='title',
        ),
        migrations.AddField(
            model_name='propositionrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'Pro'), ('CO_PROMOTEUR', 'CoPro'), ('READER', 'Reader')], default='PROMOTEUR', max_length=12),
        ),
    ]
