# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0005_adviser_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='type',
            field=models.CharField(choices=[('MGR', 'Manager'), ('PRF', 'Professor')], default='PRF', max_length=3),
        ),
    ]
