# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0006_adviser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='adviser',
            name='type',
            field=models.CharField(choices=[('PRF', 'Professor'), ('MGR', 'Manager')], default='PRF', max_length=3),
        ),
    ]
