# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_auto_20160714_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='defend_year',
            field=models.CharField(choices=[('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020')], default='2016', max_length=4),
        ),
    ]
