# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0007_auto_20160428_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositiondissertation',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
