# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_add_initial_users_to_groups'),
        ('dissertation', '0007_auto_20160714_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='defend_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear'),
        ),
    ]
