# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0008_propositiondissertation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositiondissertation',
            old_name='active',
            new_name='actived',
        ),
    ]
