# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0009_auto_20160429_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositiondissertation',
            old_name='actived',
            new_name='active',
        ),
    ]
