# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-16 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0009_auto_20160726_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertationupdate',
            name='justification',
            field=models.TextField(default=''),
        ),
    ]
