# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0010_auto_20160816_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproposition',
            name='readers_visibility_date_for_students',
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='end_edit_title',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='end_jury_visibility',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='start_edit_title',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='start_jury_visibility',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
