# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0010_auto_20160429_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproposition',
            name='proposition_dissertation',
        ),
        migrations.AddField(
            model_name='propositiondissertation',
            name='offer_propositions',
            field=models.ManyToManyField(to='dissertation.OfferProposition'),
        ),
    ]
