# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0011_auto_20160429_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='propositiondissertation',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
