# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-29 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0012_propositiondissertation_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propositiondissertation',
            old_name='offer_propositions',
            new_name='offer_proposition',
        ),
    ]
