# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0012_propositiondissertation_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='type',
            field=models.CharField(choices=[('PRF', 'professor'), ('MGR', 'manager')], default='PRF', max_length=3),
        ),
        migrations.AlterField(
            model_name='dissertationrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'promotor'), ('CO_PROMOTEUR', 'copromotor'), ('READER', 'reader')], max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='collaboration',
            field=models.CharField(choices=[('POSSIBLE', 'possible'), ('REQUIRED', 'required'), ('FORBIDDEN', 'forbidden')], default='FORBIDDEN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='level',
            field=models.CharField(choices=[('DOMAIN', 'level_domain'), ('WORK', 'level_work'), ('QUESTION', 'level_question'), ('THEME', 'level_theme')], default='DOMAIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='type',
            field=models.CharField(choices=[('RDL', 'litterature_review'), ('EDC', 'case_study')], default='RDL', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositionrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'promotor'), ('CO_PROMOTEUR', 'copromotor'), ('READER', 'reader')], default='PROMOTEUR', max_length=12),
        ),
    ]
