# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0013_auto_20160429_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='adviser_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='commission_readers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='commission_validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='evaluation_first_cicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='visibility_commission_readers',
            field=models.BooleanField(default=False),
        ),
    ]
