# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0014_auto_20160916_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='DissertationLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='dissertation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, to='dissertation.DissertationLocation'),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(blank=True, choices=[('JANUARY', 'january'), ('JUNE', 'june'), ('SEPTEMBER', 'september')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.CharField(blank=True, choices=[('2016', '2016-2017'), ('2017', '2017-2018'), ('2018', '2018-2019'), ('2019', '2019-2020'), ('2020', '2020-2021'), ('2021', '2021-2022'), ('2022', '2022-2023'), ('2023', '2023-2024'), ('2024', '2024-2025'), ('2025', '2025-2026')], max_length=4, null=True),
        ),
    ]
