# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-03 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0014_auto_20160503_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyadviser',
            name='adviser',
        ),
        migrations.RemoveField(
            model_name='facultyadviser',
            name='structure',
        ),
        migrations.DeleteModel(
            name='FacultyAdviser',
        ),
    ]
