# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0015_auto_20160916_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propositiondissertation',
            name='level',
            field=models.CharField(choices=[('SPECIFIC', 'specific_subject'), ('THEME', 'large_theme')], default='DOMAIN', max_length=12),
        ),
        migrations.AlterField(
            model_name='propositiondissertation',
            name='type',
            field=models.CharField(choices=[('RDL', 'litterature_review'), ('EMP', 'empirical_research'), ('THE', 'theoretical_analysis'), ('PRO', 'project_dissertation'), ('DEV', 'development_dissertation'), ('OTH', 'other')], default='OTH', max_length=12),
        ),
    ]
