# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0015_auto_20160504_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerproposition',
            old_name='adviser_reader',
            new_name='adviser_can_suggest_reader',
        ),
        migrations.RenameField(
            model_name='offerproposition',
            old_name='commission_validation',
            new_name='evaluation_first_year',
        ),
        migrations.RenameField(
            model_name='offerproposition',
            old_name='evaluation_first_cicle',
            new_name='readers_visibility_date_for_students',
        ),
        migrations.RenameField(
            model_name='offerproposition',
            old_name='commission_readers',
            new_name='student_can_manage_readers',
        ),
        migrations.RenameField(
            model_name='offerproposition',
            old_name='visibility_commission_readers',
            new_name='validation_commission_exists',
        ),
    ]
