# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0017_auto_20160512_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproposition',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Structure'),
        ),
    ]
