# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-26 12:56
from __future__ import unicode_literals

from django.db import migrations
import uuid
from dissertation.models.adviser import Adviser


def populate_adviser_uuid(apps, schema_editor):
    advisers = Adviser.objects.all()
    for adviser in advisers:
        adviser.update(uuid=uuid.uuid4())


class Migration(migrations.Migration):
    dependencies = [
        ('dissertation', '0017_add_adviser_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_adviser_uuid),
    ]
