# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0018_auto_20160512_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerproposition',
            name='title',
        ),
    ]
