# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0019_remove_offerproposition_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerproposition',
            old_name='offer_year',
            new_name='structure',
        ),
    ]
