# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0021_facultyadviser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyadviser',
            old_name='author',
            new_name='adviser',
        ),
    ]
