# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20160512_0917'),
        ('dissertation', '0022_auto_20160512_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyadviser',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='offerproposition',
            name='structure',
        ),
        migrations.AddField(
            model_name='facultyadviser',
            name='offer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='offer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.Offer'),
            preserve_default=False,
        ),
    ]
