# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0023_auto_20160513_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='acronym',
            field=models.CharField(default='1', max_length=200),
            preserve_default=False,
        ),
    ]
