# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0023_populate_uuid_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertation',
            name='defend_periode',
            field=models.CharField(blank=True, choices=[('UNDEFINED', 'undefined'), ('JANUARY', 'january'), ('JUNE', 'june'), ('SEPTEMBER', 'september')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='defend_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
