# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 11:36
from __future__ import unicode_literals
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0024_auto_20161010_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_proposition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.OfferProposition')),
                ('proposition_dissertation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.PropositionDissertation')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
