# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20160512_0917'),
        ('dissertation', '0024_offerproposition_acronym'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='dissertation',
            name='learning_unit_enrollment',
        ),
        migrations.AddField(
            model_name='dissertation',
            name='offer_year_start',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
            preserve_default=False,
        ),
    ]
