# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0025_auto_20160513_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='prom',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dissertation.Adviser'),
            preserve_default=False,
        ),
    ]
