# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0026_dissertation_prom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertationrole',
            name='dissertation',
        ),
        migrations.AlterField(
            model_name='dissertation',
            name='prom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dissertation.DissertationRole'),
        ),
    ]
