# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0027_auto_20160513_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertationrole',
            name='title',
        ),
        migrations.AddField(
            model_name='dissertationrole',
            name='status',
            field=models.CharField(choices=[('PRO', 'Pro'), ('CO_PRO', 'CoPro'), ('READER', 'Reader')], default='1', max_length=12),
            preserve_default=False,
        ),
    ]
