# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0028_auto_20170410_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propositionoffer',
            options={'ordering': ['offer_proposition__acronym']},
        ),
    ]
