# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0028_auto_20160513_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dissertation',
            name='prom',
        ),
        migrations.AddField(
            model_name='dissertationrole',
            name='dissertation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='dissertation.Dissertation'),
            preserve_default=False,
        ),
    ]
