# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 12:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20160512_0917'),
        ('dissertation', '0029_auto_20160513_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.Student'),
            preserve_default=False,
        ),
    ]
