# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-03 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0029_auto_20170428_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPropositionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name_short', models.CharField(max_length=10)),
                ('name_long', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='propositionoffer',
            options={'ordering': ['offer_proposition__acronym']},
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='offer_proposition_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.OfferPropositionGroup'),
        ),
    ]
