# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-20 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0030_dissertation_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dissertationrole',
            name='status',
            field=models.CharField(choices=[('PROMOTEUR', 'Pro'), ('CO_PROMOTEUR', 'CoPro'), ('READER', 'Reader')], max_length=12),
        ),
    ]
