# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0031_auto_20170704_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproposition',
            name='offer_proposition_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dissertation.OfferPropositionGroup'),
        ),
    ]
