# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0033_auto_20160526_1125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adviser',
            options={'ordering': ['person__last_name', 'person__middle_name', 'person__first_name']},
        ),
        migrations.AlterModelOptions(
            name='dissertation',
            options={'ordering': ['author__person__last_name', 'author__person__middle_name', 'author__person__first_name', 'title']},
        ),
        migrations.AlterModelOptions(
            name='propositiondissertation',
            options={'ordering': ['author__person__last_name', 'author__person__middle_name', 'author__person__first_name', 'title']},
        ),
    ]
