# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0034_auto_20160607_1714'),
        ('dissertation', '0034_auto_20160608_1021'),
    ]

    operations = [
    ]
