# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-17 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dissertation', '0036_auto_20160617_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerproposition',
            name='day_of_month_end_visibility_dissertation',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='day_of_month_end_visibility_proposition',
            field=models.IntegerField(default=31),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='month_end_visibility_dissertation',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='offerproposition',
            name='month_end_visibility_proposition',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='day_of_month_start_visibility_dissertation',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='day_of_month_start_visibility_proposition',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='month_start_visibility_dissertation',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='offerproposition',
            name='month_start_visibility_proposition',
            field=models.IntegerField(default=9),
        ),
    ]
