# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-21 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_remove_uuid_null'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externaloffer',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='externaloffer',
            name='grade_type',
        ),
        migrations.RemoveField(
            model_name='externaloffer',
            name='offer_year',
        ),
        migrations.DeleteModel(
            name='ExternalOffer',
        ),
    ]
