# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-04 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20160921_1139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssimilationCriteria',
        ),
    ]
