# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals
from django.conf import settings

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_auto_20160921_1139'),
    ]

    operations = [
        migrations.AddField(
         model_name='gradetype',
         name='institutional_grade_type_enum',
         field=models.CharField(blank=True, choices=[('BACHELOR', 'BACHELOR'), ('MASTER_60', 'MASTER_60'),
                                                     ('MASTER_120', 'MASTER_120'), ('MASTER_180_OR_240', 'MASTER_180_OR_240'),
                                                     ('ADVANCED_MASTER', 'ADVANCED_MASTER'), ('TRAINING_CERTIFICATE', 'TRAINING_CERTIFICATE'),
                                                     ('CERTIFICATE', 'CERTIFICATE'), ('DOCTORATE', 'DOCTORATE'),
                                                     ('CAPAES', 'CAPAES')], max_length=25, null=True),
        ),
    ]
