# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-20 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0013_auto_20170215_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='recognized',
            field=models.BooleanField(default=False),
        ),
    ]
