# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals
from django.db import migrations
from base.models import attribution as base_attribution


def move_data_from_base_attribution_to_attribution(apps, schema_editor):
    for b_attribution in base_attribution.Attribution.objects.raw('SELECT * FROM base_attribution'):
        migrations.RunSQL("""
          INSERT INTO attribution_attribution
              (external_id, changed, start_date, end_date, function, learning_unit_year_id, tutor)
          VALUES ({}, {}, {}, {}, {}, {}, {});""".format(b_attribution.external_id,
                                                         b_attribution.changed,
                                                         b_attribution.start_date,
                                                         b_attribution.end_date,
                                                         b_attribution.function,
                                                         b_attribution.learning_unit_year_id,
                                                         b_attribution.tutor))


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(move_data_from_base_attribution_to_attribution),
    ]