# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals
from django.db import migrations
from attribution.models import attribution


def set_coordinators_as_score_responsible(apps, schema_editor):
    attributions = attribution.Attribution.objects.all()
    for an_attribution in attributions:
        if an_attribution.function == 'COORDINATOR':
            an_attribution.score_responsible = True
            an_attribution.save()


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0004_attribution_score_responsible'),
    ]

    operations = [
        migrations.RunPython(set_coordinators_as_score_responsible),
    ]
