# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0005_from_coordinator_to_score_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributioncharge',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='attributioncharge',
            name='allocation_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
