# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals
import uuid
from django.db import migrations
from base.models import attribution as base_attribution
from django.db import connection
from django.db import transaction


@transaction.atomic
def move_data_from_base_attribution_to_attribution(apps, schema_editor):
    base_attributions = base_attribution.Attribution.objects.raw('SELECT * FROM base_attribution')
    with connection.cursor() as cursor:
        for b_attribution in base_attributions:
            print(b_attribution)
            query = """
                INSERT INTO attribution_attribution
                    (external_id, changed, start_date, end_date, function, learning_unit_year_id, tutor_id, score_responsible, uuid)
                VALUES ({}, {}, {}, {}, {}, {}, {}, {}, {});""".format("'" + str(b_attribution.external_id) + "'" if b_attribution.external_id else 'null',
                                                               "'" + str(b_attribution.changed) + "'" if b_attribution.changed else 'null',
                                                               "'" + str(b_attribution.start_date) + "'" if b_attribution.start_date else 'null',
                                                               "'" + str(b_attribution.end_date) + "'" if b_attribution.end_date else 'null',
                                                               "'" + str(b_attribution.function) + "'" if b_attribution.function else 'null',
                                                               b_attribution.learning_unit_year.pk if b_attribution.learning_unit_year.pk else 'null',
                                                               b_attribution.tutor.pk if b_attribution.tutor.pk else 'null',
                                                               'true' if b_attribution.function == 'COORDINATOR' else 'false',
                                                               "'" + str(uuid.uuid4()) + "'")
            print(query)
            cursor.execute(query)


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0009_uuid_not_null'),
        ('base', '0088_auto_20170106_1728')
    ]

    operations = [
        migrations.RunPython(move_data_from_base_attribution_to_attribution),
    ]
