# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals
import uuid
from django.db import migrations
from django.db import connection
from django.db import transaction


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0009_uuid_not_null'),
        ('base', '0088_auto_20170106_1728')
    ]


