# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0010_move_data_from_base_attribution_to_attribution_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attribution',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
