# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-07 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0012_auto_20170203_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='changed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
