# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0013_auto_20170607_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
    ]
