# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribution', '0014_auto_20170627_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
