# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0016_auto_20160224_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InternshipMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('civility', models.CharField(blank=True, choices=[('PROFESSOR', 'Professor'), ('DOCTOR', 'Doctor')], max_length=20, null=True)),
                ('type_mastery', models.CharField(blank=True, choices=[('SPECIALIST', 'Specialist'), ('GENERALIST', 'Generalist')], max_length=20, null=True)),
                ('speciality', models.CharField(blank=True, choices=[('INTERNAL_MEDICINE', 'Internal Medicine'), ('SURGERY', 'Surgery'), ('GYNEC_OBSTETRICS', 'Gynec-Obstetrics'), ('PEDIATRICS', 'Pediatrics'), ('EMERGENCY', 'Emergency'), ('GERIATRICS', 'Geriatrics')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternshipOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('maximum_enrollments', models.IntegerField()),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='internship_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipOffer'),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AddField(
            model_name='internshipmaster',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='internship_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipOffer'),
        ),
        migrations.AddField(
            model_name='internshipenrollment',
            name='learning_unit_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitEnrollment'),
        ),
    ]
