# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_auto_20160122_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('learning_unit_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.LearningUnitEnrollment')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Organization')),
            ],
        ),
    ]
