# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-17 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0005_auto_20160506_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipchoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
    ]
