# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-27 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_auto_20160623_1647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internshipoffer',
            options={'permissions': (('is_internship_manager', 'Is Internship Manager'),)},
        ),
    ]
