# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0006_auto_20160627_1532'),
        ('internship', '0008_internship_manager_permission'),
    ]

    operations = [
    ]
