# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-29 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0009_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipenrollment',
            name='learning_unit_enrollment',
        ),
    ]
