# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-01 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0011_auto_20160701_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipmaster',
            name='civility',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='speciality',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='type_mastery',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
