# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0015_internshipspeciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
    ]
