# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0016_internshipspeciality_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipspeciality',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
