# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_merge'),
        ('internship', '0017_auto_20160704_2259'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternshipStudentAffectationStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('consecutive_month', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.Period')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Student')),
            ],
        ),
    ]
