# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-04 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0017_auto_20160704_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipchoice',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='internshipoffer',
            name='learning_unit_year',
        ),
        migrations.AddField(
            model_name='internshipchoice',
            name='speciality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internshipoffer',
            name='speciality',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.InternshipSpeciality'),
            preserve_default=False,
        ),
    ]
