# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0018_internshipstudentaffectationstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
