# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_auto_20160715_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentinformation',
            name='check_coordonates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='check_coordonates',
            field=models.BooleanField(default=False),
        ),
    ]
