# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0019_auto_20160715_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='acronym',
            field=models.CharField(default=' ', max_length=125),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='acronym',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(blank=True, default='service partner', max_length=30, null=True),
        ),
    ]
