# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-15 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0020_auto_20160715_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipstudentaffectationstat',
            name='type_of_internship',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
