# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-23 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_auto_20160817_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipchoice',
            name='internship_choice',
            field=models.IntegerField(default=0),
        ),
    ]
