# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-02 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0021_internshipstudentaffectationstat_type_of_internship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipstudentinformation',
            name='check_coordonates',
        ),
        migrations.RemoveField(
            model_name='organizationaddress',
            name='check_coordonates',
        ),
    ]
