# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-08 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0022_auto_20160802_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipspeciality',
            name='acronym',
            field=models.CharField(default=' ', max_length=125),
            preserve_default=False,
        ),
    ]
