# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0024_internshipspeciality_order_postion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationGenerationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
            ],
        ),
    ]
