# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-05 09:13
from __future__ import unicode_literals
from django.core.exceptions import FieldDoesNotExist
from django.db import migrations, models
import uuid


def set_uuids_model(apps, model):
    internship = apps.get_app_config('internship')
    model_class = internship.get_model(model)
    ids = model_class.objects.values_list('id', flat=True)
    if ids:
        for pk in ids:
            try:
                model_class.objects.filter(pk=pk).update(uuid=uuid.uuid4())
            except FieldDoesNotExist:
                break


def set_uuid_field(apps, schema_editor):
    set_uuids_model(apps, "internshipchoice")
    set_uuids_model(apps, "internshipmaster")
    set_uuids_model(apps, "internshipoffer")
    set_uuids_model(apps, "internshipspeciality")
    set_uuids_model(apps, "internshipstudentaffectationstat")
    set_uuids_model(apps, "internshipstudentinformation")
    set_uuids_model(apps, "organization")
    set_uuids_model(apps, "organizationaddress")
    set_uuids_model(apps, "period")


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20170105_1315'),
    ]

    operations = [
        migrations.RunPython(set_uuid_field),

        migrations.AlterField(
            model_name='internshipchoice',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipmaster',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipspeciality',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipstudentaffectationstat',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='internshipstudentinformation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]

