# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-10 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0033_auto_20170308_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipenrollment',
            name='internship_choice',
            field=models.IntegerField(default=0),
        ),
    ]
