# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-16 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20170306_0953'),
        ('internship', '0034_internshipenrollment_internship_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('students', models.ManyToManyField(to='base.Student')),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='cohort',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='internship.Cohort'),
            preserve_default=False,
        ),
    ]
