# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from internship.models.cohort import Cohort
from internship.models.internship_offer import InternshipOffer


def assign_first_cohort_to_periods(apps, schema_editor):
    cohort = Cohort.objects.first()
    for period in InternshipOffer.objects.all():
        period.cohort = cohort
        period.save()


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0035_auto_20170316_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipoffer',
            name='cohort',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='internship.Cohort'),
            preserve_default=False,
        ),
        migrations.RunPython(assign_first_cohort_to_periods),
        migrations.RunSQL(
            "ALTER TABLE internship_internshipoffer ALTER COLUMN cohort_id SET NOT NULL",
            reverse_sql="ALTER TABLE internship_internshipoffer ALTER COLUMN cohort_id DROP NOT NULL",
        )
    ]
