# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 14:01
from __future__ import unicode_literals

from django.db import migrations
from internship.models.internship_student_information import InternshipStudentInformation
from base.models.person import Person

def cleanupStudentInternshipsAndPersons(apps, schema_editor):
    bad_student_infos = InternshipStudentInformation.objects.filter(cohort_id=2)
    bad_person_ids = bad_student_infos.values_list("person_id", flat=True)
    Person.objects.filter(id__in=bad_person_ids).delete()
    bad_student_infos.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0046_auto_20170410_1322'),
    ]

    operations = [
        migrations.RunPython(cleanupStudentInternshipsAndPersons)
    ]
