# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-26 09:45
from __future__ import unicode_literals

from django.db import migrations
from internship.models.internship_choice import InternshipChoice
from internship.models.internship import Internship

def cleanup_old_choices(apps, schema_editor):
    InternshipChoice.objects.filter(internship_id=0).delete()
    Internship.objects.filter(pk=0).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0047_auto_20170410_1601'),
    ]

    operations = [
        migrations.RunPython(cleanup_old_choices),
    ]
