# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 22:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0050_affectationgenerationtime_cohort'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internshipspeciality',
            old_name='order_postion',
            new_name='order_position',
        ),
    ]
