# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_person_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamEnrollmentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_final', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('justification_final', models.CharField(choices=[('ABSENT', 'Absent'), ('CHEATING', 'Cheating'), ('ILL', 'Ill'), ('JUSTIFIED_ABSENCE', 'Justified absence'), ('SCORE_MISSING', 'Score missing')], max_length=20, null=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('exam_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ExamEnrollment')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
            ],
        ),
    ]
