# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 13:31
from __future__ import unicode_literals

from django.db import migrations, models


def create_trigger_for_changed_field(table_name):
    """
    Crée et renvoie un code sql qui crée trigger pour le champs "changed"
    dans la table/modèle passée en paramètre.

    :param table_name: Nom de la table/modèle dans laquelle il faut créer un trigger.
    """
    table_name = table_name.lower()
    return "CREATE TRIGGER update_" + table_name + "_modtime BEFORE INSERT OR UPDATE ON base_" + table_name + " FOR EACH ROW EXECUTE PROCEDURE update_changed_column();"



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20160209_1659'),
    ]

    operations = [
        migrations.RunSQL(
        """CREATE OR REPLACE FUNCTION update_changed_column()
        RETURNS TRIGGER AS $$
        BEGIN
            -- Si on ne fournit pas de nouvelle date
            IF (NEW.changed IS NULL) OR (NEW.changed = OLD.changed) THEN
                NEW.changed := now();
                RETURN NEW;
            END IF;
            -- Condition ci-dessous pour si jamais le record a été modifié entre
            -- le début et la fin de (ou pendant) l'exécution du script de synchronisation
            IF (OLD.changed > NEW.changed) THEN
                NEW.changed := OLD.changed;
            END IF;
            RETURN NEW;
        END;
        $$ language 'plpgsql';"""
        ),

        migrations.RunSQL(
            create_trigger_for_changed_field('person'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('tutor'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('student'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('organization'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('structure'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('programmemanager'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('academicyear'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('academiccalendar'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offer'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offeryear'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offerenrollment'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('offeryearcalendar'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('learningunit'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('attribution'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('learningunityear'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('learningunitenrollment'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('sessionexam'),
        ),
        migrations.RunSQL(
            create_trigger_for_changed_field('examenrollment'),
        )
    ]
