# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20160222_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='highlight_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='highlight_shortcut',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='highlight_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offeryearcalendar',
            name='customized',
            field=models.BooleanField(default=False),
        ),
    ]
