# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-03 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20160303_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmemanager',
            name='faculty',
        ),
        migrations.AddField(
            model_name='programmemanager',
            name='offer_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),
    ]
