# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20160303_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeryear',
            name='grade',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'Bachelor'), ('MASTER', 'Master'), ('DOCTORATE', 'Ph.D')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offeryear',
            name='title_international',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offeryear',
            name='title_printable',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='offeryear',
            name='title_short',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
