# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20160306_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='acronym',
        ),
    ]
