# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20160306_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('template', models.TextField()),
                ('format', models.CharField(choices=[('PLAIN', 'Plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'Plain and HTML')], max_length=15)),
                ('language', models.CharField(choices=[('FR', 'Français'), ('EN', 'English')], default='FR', max_length=30, null=True)),
            ],
        ),
    ]
