# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_offerform_offertraining'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('required', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='OfferTraining',
        ),
        migrations.RenameField(
            model_name='offerform',
            old_name='parent',
            new_name='offer_year',
        ),
        migrations.AddField(
            model_name='offerquestion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferForm'),
        ),
        migrations.AddField(
            model_name='offeroption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferQuestion'),
        ),
    ]
