# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('nationality', models.CharField(max_length=80, null=True)),
                ('eu', models.CharField(choices=[('T', 'True'), ('F', 'False')], max_length=1)),
                ('dialing_code', models.CharField(max_length=3)),
                ('cref_code', models.CharField(max_length=3, null=True)),
                ('continent', models.CharField(max_length=80)),
            ],
        ),
    ]
