# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-16 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_countries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Continent'),
        ),
    ]
