# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_organization_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='structure',
            name='type',
            field=models.CharField(blank=True, choices=[('SECTOR', 'Sector'), ('FACULTY', 'Faculty'), ('INSTITUTE', 'Institute'), ('POLE', 'Pole')], default='UNKNOWN', max_length=30, null=True),
        ),
    ]
