# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20160329_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerquestion',
            name='required',
            field=models.BooleanField(default=1),
        ),
    ]
