# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20160329_1514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferForm',
            new_name='Form',
        ),
        migrations.RenameModel(
            old_name='OfferOption',
            new_name='Option',
        ),
        migrations.RenameModel(
            old_name='OfferQuestion',
            new_name='Question',
        ),
    ]
