# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-12 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20160406_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollment',
            name='encoding_status',
            field=models.CharField(blank=True, choices=[('SAVED', 'saved'), ('SUBMITTED', 'submitted')], max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_draft',
            field=models.CharField(blank=True, choices=[('ABSENT', 'absent'), ('CHEATING', 'cheating'), ('ILL', 'ill'), ('JUSTIFIED_ABSENCE', 'justified_absence'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_final',
            field=models.CharField(blank=True, choices=[('ABSENT', 'absent'), ('CHEATING', 'cheating'), ('ILL', 'ill'), ('JUSTIFIED_ABSENCE', 'justified_absence'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_reencoded',
            field=models.CharField(blank=True, choices=[('ABSENT', 'absent'), ('CHEATING', 'cheating'), ('ILL', 'ill'), ('JUSTIFIED_ABSENCE', 'justified_absence'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollmenthistory',
            name='justification_final',
            field=models.CharField(choices=[('ABSENT', 'absent'), ('CHEATING', 'cheating'), ('ILL', 'ill'), ('JUSTIFIED_ABSENCE', 'justified_absence'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='format',
            field=models.CharField(choices=[('PLAIN', 'plain'), ('HTML', 'HTML'), ('PLAIN_HTML', 'plain_and_html')], max_length=15),
        ),
        migrations.AlterField(
            model_name='offeryear',
            name='grade',
            field=models.CharField(blank=True, choices=[('BACHELOR', 'bachelor'), ('MASTER', 'master'), ('DOCTORATE', 'ph_d')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'female'), ('M', 'male'), ('U', 'unknown')], default='U', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexam',
            name='status',
            field=models.CharField(choices=[('IDLE', 'idle'), ('OPEN', 'open'), ('CLOSED', 'closed')], max_length=10),
        ),
    ]
