# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20160317_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languages',
            new_name='Language',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
