# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20160317_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
    ]
