# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20160413_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offeryearcalendar',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='offeryearcalendar',
            name='start_date',
        ),
        migrations.AddField(
            model_name='offeryearcalendar',
            name='_end_date',
            field=models.DateField(blank=True, db_column='end_date', null=True),
        ),
        migrations.AddField(
            model_name='offeryearcalendar',
            name='_start_date',
            field=models.DateField(blank=True, db_column='start_date', null=True),
        ),
    ]
