# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Currency'),
        ),
    ]
