# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_applicationnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offeryearcalendar',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
