# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_auto_20160414_1720'),
        ('base', '0031_applicationnotice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StructureAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('fax', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Country')),
            ],
        ),
        migrations.AddField(
            model_name='personaddress',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RunSQL(
            "delete from base_organizationaddress;"
        ),
        migrations.AlterField(
            model_name='organizationaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
        migrations.RunSQL(
            "delete from base_personaddress;"
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
        migrations.AlterField(
            model_name='personaddress',
            name='label',
            field=models.CharField(choices=[('RESIDENTIAL', 'residential'), ('PROFESSIONAL', 'professional')], max_length=20),
        ),
        migrations.AddField(
            model_name='structureaddress',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Structure'),
        ),
    ]
