# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-17 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_country_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=2)),
                ('code', models.CharField(max_length=80)),
                ('admin1', models.CharField(blank=True, max_length=1, null=True)),
                ('admin2', models.CharField(blank=True, max_length=3, null=True)),
                ('admin3', models.CharField(blank=True, max_length=3, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Country')),
            ],
        ),
    ]
