# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20160419_1612'),
    ]

    operations = [
        migrations.RunSQL(
            "delete from base_programmemanager;"
        ),
        migrations.RenameModel('ProgrammeManager', 'ProgramManager'),
        migrations.AddField(
            model_name='programmanager',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='programmanager',
            name='offer_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
        ),

    ]
