# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-21 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20160421_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
    ]
