# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20160318_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='code',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
