# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_continent_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
