# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-25 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20160421_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
