# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20160318_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='continent',
            name='code',
            field=models.CharField(default='', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
