# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-02 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20160428_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(blank=True, choices=[('SECTOR', 'sector'), ('FACULTY', 'faculty'), ('INSTITUTE', 'institute'), ('POLE', 'pole'), ('DOCTORAL_COMMISSION', 'doctoral_commission'), ('PROGRAM_COMMISSION', 'program_commission'), ('LOGISTIC', 'logistic'), ('UNDEFINED', 'undefined'), ('RESEARCH_CENTER', 'research_center'), ('TECHNOLOGIC_PLATFORM', 'technologic_platform')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(max_length=10),
        ),
    ]
