# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-04 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20160502_1151'),
        ('base', '0039_auto_20160502_0055'),
    ]

    operations = [
    ]
