# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_messagehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagehistory',
            name='origin',
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
