# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-09 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20160506_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentfile',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
