# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20160509_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examenrollment',
            name='encoding_status',
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_draft',
            field=models.CharField(blank=True, choices=[('ABSENCE_UNJUSTIFIED', 'absence_unjustified'), ('ABSENCE_JUSTIFIED', 'absence_justified'), ('CHEATING', 'cheating'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_final',
            field=models.CharField(blank=True, choices=[('ABSENCE_UNJUSTIFIED', 'absence_unjustified'), ('ABSENCE_JUSTIFIED', 'absence_justified'), ('CHEATING', 'cheating'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_reencoded',
            field=models.CharField(blank=True, choices=[('ABSENCE_UNJUSTIFIED', 'absence_unjustified'), ('ABSENCE_JUSTIFIED', 'absence_justified'), ('CHEATING', 'cheating'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollmenthistory',
            name='justification_final',
            field=models.CharField(choices=[('ABSENCE_UNJUSTIFIED', 'absence_unjustified'), ('ABSENCE_JUSTIFIED', 'absence_justified'), ('CHEATING', 'cheating'), ('SCORE_MISSING', 'score_missing')], max_length=20, null=True),
        ),
    ]
