# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-11 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20160504_1414'),
        ('base', '0043_auto_20160509_0748'),
    ]

    operations = [
    ]
