# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
