# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-23 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_person_birth_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programmanager',
            unique_together=set([('person', 'offer_year')]),
        ),
    ]
