# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20160523_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexam',
            name='deadline',
            field=models.DateField(null=True),
        ),
    ]
