# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-26 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_scoresencoding'),
        ('base', '0045_auto_20160512_0917'),
    ]

    operations = [
    ]
