# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-29 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_auto_20160527_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionexam',
            name='status',
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_draft',
            field=models.CharField(blank=True, choices=[('ABSENCE_UNJUSTIFIED', 'Absence injustifiée'), ('ABSENCE_JUSTIFIED', 'Absence justifiée'), ('CHEATING', 'Tricherie'), ('SCORE_MISSING', 'Note manquante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_final',
            field=models.CharField(blank=True, choices=[('ABSENCE_UNJUSTIFIED', 'Absence injustifiée'), ('ABSENCE_JUSTIFIED', 'Absence justifiée'), ('CHEATING', 'Tricherie'), ('SCORE_MISSING', 'Note manquante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='justification_reencoded',
            field=models.CharField(blank=True, choices=[('ABSENCE_UNJUSTIFIED', 'Absence injustifiée'), ('ABSENCE_JUSTIFIED', 'Absence justifiée'), ('CHEATING', 'Tricherie'), ('SCORE_MISSING', 'Note manquante')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='examenrollmenthistory',
            name='justification_final',
            field=models.CharField(choices=[('ABSENCE_UNJUSTIFIED', 'Absence injustifiée'), ('ABSENCE_JUSTIFIED', 'Absence justifiée'), ('CHEATING', 'Tricherie'), ('SCORE_MISSING', 'Note manquante')], max_length=20, null=True),
        ),
    ]
