# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20160529_2355'),
        ('base', '0052_merge'),
    ]

    operations = [
    ]
