# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_auto_20160529_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='read_in_myosis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='show_in_myosis',
            field=models.BooleanField(default=True),
        ),
    ]
