# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_scoresencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagehistory',
            name='read_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagehistory',
            name='show_to_user',
            field=models.BooleanField(default=True),
        ),
    ]
