# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 12:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_message_history_modifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academiccalendar',
            options={'permissions': (('can_acces_academic_clendar', 'Can access academic calendar'),)},
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'permissions': (('can_access_academicyear', 'Can access academic year'),)},
        ),
        migrations.AlterModelOptions(
            name='learningunit',
            options={'permissions': (('can_acces_leaningunit', 'Can access learning unit'),)},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'permissions': (('can_access_offer', 'Can access offer'),)},
        ),
        migrations.AlterModelOptions(
            name='offerenrollment',
            options={'permissions': (('can_acces_student_path', 'Can access student path'), ('can_acces_evaluation', 'Can access evaluation'))},
        ),
        migrations.AlterModelOptions(
            name='offeryear',
            options={'permissions': (('can_acces_offeryear', 'Can access offeryear'),)},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'permissions': (('can_acces_organization', 'Can access organization'),)},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'permissions': (('is_administrator', 'Is administrator'),)},
        ),
        migrations.AlterModelOptions(
            name='scoresencoding',
            options={'managed': False, 'permissions': (('can_acces_scoreencoding', 'Can access scoreencoding'),)},
        ),
        migrations.AlterModelOptions(
            name='structure',
            options={'permissions': (('can_acces_structure', 'Can access structure'),)},
        ),
    ]
