# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 12:18
from __future__ import unicode_literals
from django.core.management.sql import emit_post_migrate_signal

from django.db import migrations, models
from base.models.program_manager import ProgramManager
from base.models.student import Student
from base.models.tutor import Tutor


def add_administrators_group(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    administrators_group, created = Group.objects.get_or_create(name='administrators')
    if created:
        is_admin_perm = Permission.objects.get(codename='is_administrator')
        administrators_group.permissions.add(is_admin_perm)


def add_init_tutors_group(apps, schema_editor):
    # create group
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    tutors_group, created = Group.objects.get_or_create(name='tutors')
    if created:
        # Add permissions to group
        offers_perm = Permission.objects.get(codename='can_access_offer')
        offers_years_perm = Permission.objects.get(codename='can_acces_offeryear')
        student_path_perm = Permission.objects.get(codename='can_acces_student_path')
        evaluation_perm = Permission.objects.get(codename='can_acces_evaluation')
        score_encoding_perm = Permission.objects.get(codename='can_acces_scoreencoding')
        tutors_group.permissions.add(offers_perm, student_path_perm, offers_years_perm, evaluation_perm, score_encoding_perm)

        # Add existing users to group
        [tutor.person.user.groups.add(tutors_group) for tutor in list(Tutor.objects.all())]


def add_init_pgm_managers_group(apps, schema_editor):
    # create group
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    pgm_managers_group, created = Group.objects.get_or_create(name='program_managers')
    if created:
        # Add permissions to group
        offers_perm = Permission.objects.get(codename='can_access_offer')
        offers_years_perm = Permission.objects.get(codename='can_acces_offeryear')
        student_path_perm = Permission.objects.get(codename='can_acces_student_path')
        evaluation_perm = Permission.objects.get(codename='can_acces_evaluation')
        score_encoding_perm = Permission.objects.get(codename='can_acces_scoreencoding')
        academic_year_perm = Permission.objects.get(codename='can_access_academicyear')
        academic_calendar_perm = Permission.objects.get(codename='can_acces_academic_clendar')
        pgm_managers_group.permissions.add(offers_perm, student_path_perm, offers_years_perm, evaluation_perm, score_encoding_perm,
                              academic_year_perm,academic_calendar_perm)

        # Add existing users to group
        [pgm_managers.person.user.groups.add(pgm_managers_group) for pgm_managers in list(ProgramManager.objects.all())]


def add_init_students_group(apps, schema_editor):
    # create group
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    student_group, created = Group.objects.get_or_create(name='students')
    if created:
        # Add permissions to group
        student_path_perm = Permission.objects.get(codename='can_acces_student_path')
        student_group.permissions.add(student_path_perm)

        # Add existing users to group
        [student.person.user.groups.add(student_group) for student in list(Student.objects.all())]


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_create_permissions'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(add_administrators_group),
        migrations.RunPython(add_init_tutors_group),
        migrations.RunPython(add_init_pgm_managers_group),
        migrations.RunPython(add_init_students_group),
    ]