# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-16 11:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_merge'),
        ('base', '0054_scoresencoding'),
    ]

    operations = [
    ]
