# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-08 12:18
from __future__ import unicode_literals
from django.contrib.auth.models import Group, User
from django.core.management.sql import emit_post_migrate_signal

from django.db import migrations
from base.models import tutor, program_manager, student


def add_users_to_group(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    emit_post_migrate_signal(2, False, db_alias)
    tutors_group = Group.objects.get(name='tutors')
    pgm_managers_group = Group.objects.get(name='program_managers')
    students_group = Group.objects.get(name='students')
    for user in list(User.objects.all()):
        person = person.find_by_user(user)
        if person:
            # Check Tutor
            if tutor.find_by_person(person) and tutors_group:
                user.groups.add(tutors_group)
            # Check PgmManager
            if program_manager.find_by_person(person) and pgm_managers_group:
                user.groups.add(pgm_managers_group)
            # Check Student
            if student.find_by_person(person) and students_group:
                user.groups.add(students_group)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_creation_and_initialisation_of_groups'),
        ('contenttypes', '__latest__'),
    ]

    operations = [
        migrations.RunPython(add_users_to_group),
    ]