# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20160718_1435'),
        ('base', '0059_auto_20160725_1753'),
    ]

    operations = [
    ]
