# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20160902_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
