# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models
from osis_common.models.message_template import MessageTemplate as NewMessageTemplate
from osis_common.models.message_history import MessageHistory as NewMessageHistory
from osis_common.models.document_file import DocumentFile as NewDocumentFile


def migrate_message_template_data(apps, schema_editor):
    MessageTemplate = apps.get_model("base", "MessageTemplate")
    new_message_templates = [NewMessageTemplate(**old_message_template)
                             for old_message_template
                             in MessageTemplate.objects.all().values()]
    if new_message_templates:
        NewMessageTemplate.objects.bulk_create(new_message_templates)


def migrate_message_history(apps, schema_editor):
    MessageHistory = apps.get_model("base", "MessageHistory")
    new_message_histories = [NewMessageHistory(**old_message_history)
                             for old_message_history
                             in MessageHistory.objects.all().values()]
    if new_message_histories:
        NewMessageHistory.objects.bulk_create(new_message_histories)


def migrate_document_file(apps, schema_editor):
    DocumentFile = apps.get_model("base", "DocumentFile")
    new_document_files = [NewDocumentFile(**old_document_file)
                         for old_document_file
                         in DocumentFile.objects.all().values()]
    if new_document_files:
        NewDocumentFile.objects.bulk_create(new_document_files)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20160902_1639'),
        ('osis_common', '0006_modifications_documentfile')
    ]


    operations = [
        migrations.RemoveField(
            model_name='documentfile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='messagehistory',
            name='person',
        ),
        migrations.DeleteModel(
            name='MessageTemplate',
        ),
        migrations.DeleteModel(
            name='DocumentFile',
        ),
        migrations.DeleteModel(
            name='MessageHistory',
        ),
    ]
