# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_migration_to_osis_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='source',
            field=models.CharField(blank=True, choices=[('BASE', 'BASE'), ('DISSERTATION', 'DISSERTATION')], max_length=25, null=True),
        ),
    ]
