# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_add_learning_unit_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='learning_unit',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnit'),
        ),
    ]
