# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_attribution_learning_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContainerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear')),
                ('learning_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer')),
            ],
            options={
                'permissions': (('can_access_learningcontaineryear', 'Can access learning container year'),),
            },
        ),
    ]
