# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-27 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20161027_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('learning_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer')),
            ],
        ),
        migrations.CreateModel(
            name='LearningComponentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=3)),
                ('type', models.CharField(blank=True, choices=[('COURS_MAGISTRAL', 'COURS_MAGISTRAL'), ('SEMINAIRES', 'SEMINAIRES'), ('TRAVAUX_PRATIQUES', 'TRAVAUX_PRATIQUES')], max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('learning_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponent')),
                ('learning_container_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear')),
            ],
            options={
                'permissions': (('can_access_learningcomponentyear', 'Can access learning component year'),),
            },
        ),
        migrations.CreateModel(
            name='LearningUnitComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Learning_component_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear')),
            ],
            options={
                'permissions': (('can_access_learningunitcomponent', 'Can access learning unit component'),),
            },
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='learningunit',
            name='start_year',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='learning_container_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='learning_unit_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear'),
        ),
    ]
