# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-23 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_scoresencoding'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeryear',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
