# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_scoresencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structure',
            name='type',
            field=models.CharField(blank=True, choices=[('SECTOR', 'SECTOR'), ('FACULTY', 'FACULTY'), ('INSTITUTE', 'INSTITUTE'), ('POLE', 'POLE'), ('DOCTORAL_COMMISSION', 'DOCTORAL_COMMISSION'), ('PROGRAM_COMMISSION', 'PROGRAM_COMMISSION'), ('LOGISTIC', 'LOGISTIC'), ('RESEARCH_CENTER', 'RESEARCH_CENTER'), ('TECHNOLOGIC_PLATFORM', 'TECHNOLOGIC_PLATFORM'), ('UNDEFINED', 'UNDEFINED')], max_length=30, null=True),
        ),
    ]
