# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20161213_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningUnitComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], db_index=True, max_length=25, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitYear')),
            ],
            options={
                'permissions': (('can_access_learningunit', 'Can access learning unit'),),
            },
        ),
    ]
