# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-15 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_learningunitcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='team',
            field=models.BooleanField(default=False),
        ),
    ]
