# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-16 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20161215_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunitcomponent',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
