# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_academiccalendar_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
