# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-24 09:04
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0012_migrate_fk_to_enum'),
        ('base', '0095_synchronization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.IntegerField(choices=[(1, 'learning_unit_year'), (2, 'offer_year')])),
                ('label', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('published', models.BooleanField()),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TextLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.IntegerField(choices=[(1, 'learning_unit_year'), (2, 'offer_year')])),
                ('reference', models.IntegerField()),
                ('text', ckeditor.fields.RichTextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('text_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TextLabel')),
            ],
        ),
        migrations.CreateModel(
            name='TranslatedTextLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference.Language')),
                ('text_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.TextLabel')),
            ],
        ),
    ]
