# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0095_synchronization'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LearningClassYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=3)),
                ('learning_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningClass')),
            ],
            options={
                'permissions': (('can_access_learningclassyear', 'Can access learning class year'),),
            },
        ),
        migrations.CreateModel(
            name='LearningComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LearningComponentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=3)),
                ('type', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=255)),
                ('learning_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponent')),
            ],
            options={
                'permissions': (('can_access_learningunitcomponentyear', 'Can access learning unit component year'),),
            },
        ),
        migrations.CreateModel(
            name='LearningContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LearningContainerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=10)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear')),
                ('learning_container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer')),
            ],
            options={
                'permissions': (('can_access_learningcontaineryear', 'Can access learning container year'),),
            },
        ),
        migrations.CreateModel(
            name='LearningUnitComponentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_unit_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningUnitComponent')),
                ('learning_unit_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningClassYear')),
            ],
            options={
                'permissions': (('can_access_learningunitcomponentclass', 'Can access learning unit component class'),),
            },
        ),
        migrations.AddField(
            model_name='learningunit',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('ANNUAL', 'ANNUAL'), ('BIENNIAL_EVEN', 'BIENNIAL_EVEN'),
                                                        ('BIENNIAL_ODD', 'BIENNIAL_ODD')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='learning_container_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
        ),
        migrations.AddField(
            model_name='learningcomponent',
            name='learning_container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer'),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='learning_component_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear'),
        ),
        migrations.AddField(
            model_name='learningclass',
            name='learning_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponent'),
        ),
        migrations.AddField(
            model_name='learningunitcomponent',
            name='learning_component_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear', blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='learning_container_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear'),
            preserve_default=False,
        ),
    ]
