# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-06 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20170306_0953.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='periodicity',
            field=models.CharField(blank=True, choices=[('ANNUAL', 'ANNUAL'), ('BIENNIAL_EVEN', 'BIENNIAL_EVEN'), ('BIENNIAL_ODD', 'BIENNIAL_ODD')], max_length=20, null=True),
        ),
    ]
