# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20170320_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='status',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('VALID', 'VALID'), ('INVALID', 'INVALID')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='type',
            field=models.CharField(blank=True, choices=[('COURSE', 'COURSE'), ('MASTER_THESIS', 'MASTER_THESIS'), ('INTERNSHIP', 'INTERNSHIP')], max_length=20, null=True),
        ),
    ]
