# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20170320_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='structure',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='base.Structure'),
            preserve_default=False,
        ),
    ]
