# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20170320_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('number_session', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
            ],
        ),
        migrations.CreateModel(
            name='SessionExamDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deadline', models.DateField()),
                ('deadline_tutor', models.IntegerField(null=True)),
                ('number_session', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('offer_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferEnrollment')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionexam',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='sessionexam',
            name='offer_year_calendar',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexam',
            name='number_session',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AddField(
            model_name='sessionexamcalendar',
            name='academic_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicCalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexamcalendar',
            unique_together=set([('number_session', 'academic_calendar')]),
        ),
        migrations.RunSQL(
            """
            CREATE OR REPLACE VIEW app_scores_encoding AS
            SELECT row_number() OVER () as id,

                base_programmanager.id as program_manager_id,
                program_manager_person.id as pgm_manager_person_id,
                base_offeryear.id as offer_year_id,
                base_learningunityear.id as learning_unit_year_id,
                base_examenrollment.enrollment_state,

                count(base_examenrollment.id) as total_exam_enrollments,
                sum(case when base_examenrollment.score_final is not null
                              or base_examenrollment.justification_final is not null
                         then 1 else 0 end) exam_enrollments_encoded,
                sum(case when (base_examenrollment.score_draft is not null
                               and base_examenrollment.score_final is null
                               and base_examenrollment.justification_final is null)
                              or (base_examenrollment.justification_draft is not null
                                  and base_examenrollment.score_final is null
                                  and base_examenrollment.justification_final is null)
                         then 1 else 0 end) scores_not_yet_submitted

            from base_examenrollment
            join base_sessionexam on base_sessionexam.id = base_examenrollment.session_exam_id
            join base_learningunityear on base_learningunityear.id = base_sessionexam.learning_unit_year_id

            join base_learningunitenrollment on base_learningunitenrollment.id = base_examenrollment.learning_unit_enrollment_id
            join base_offerenrollment on base_offerenrollment.id = base_learningunitenrollment.offer_enrollment_id
            join base_offeryear on base_offeryear.id = base_offerenrollment.offer_year_id

            join base_programmanager on base_programmanager.offer_year_id = base_offeryear.id
            join base_person program_manager_person on program_manager_person.id = base_programmanager.person_id

            group by
            base_programmanager.id,
            program_manager_person.id,
            base_offeryear.id,
            base_learningunityear.id,
            base_examenrollment.enrollment_state
            ;
            """
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('DISSERTATION_SUBMISSION', 'DISSERTATION_SUBMISSION'), ('EXAM_ENROLLMENTS', 'EXAM_ENROLLMENTS'), ('SCORES_EXAM_DIFFUSION', 'SCORES_EXAM_DIFFUSION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION'), ('TEACHING_CHARGE_APPLICATION', 'TEACHING_CHARGE_APPLICATION')], max_length=50, null=True),
        ),
    ]
