# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-31 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20170320_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExamCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('number_session', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
            ],
        ),
        migrations.CreateModel(
            name='SessionExamDeadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('changed', models.DateTimeField(null=True)),
                ('deadline', models.DateTimeField()),
                ('deadline_tutor', models.IntegerField(null=True)),
                ('number_session', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('offer_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.OfferEnrollment')),
            ],
        ),
        migrations.RemoveField(
            model_name='sessionexam',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='sessionexam',
            name='offer_year_calendar',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='reference',
            field=models.CharField(blank=True, choices=[('DELIBERATION', 'DELIBERATION'), ('SCORES_EXAM_SUBMISSION', 'SCORES_EXAM_SUBMISSION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sessionexam',
            name='number_session',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)]),
        ),
        migrations.AddField(
            model_name='sessionexamcalendar',
            name='academic_calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicCalendar'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionexamcalendar',
            unique_together=set([('number_session', 'academic_calendar')]),
        ),
    ]
