# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 06:42
from __future__ import unicode_literals
from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20170320_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programmanager',
            options={'permissions': (('can_access_program_manager', 'Can access program manager'),)},
        ),
    ]
