# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20170331_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionexamdeadline',
            name='deadline',
            field=models.DateField(),
        ),
    ]
