# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-11 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20170407_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='working_type',
            field=models.CharField(blank=True, choices=[('MAIN', 'MAIN'), ('SECONDARY', 'SECONDARY'), ('INACTIVE', 'INACTIVE')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='working_status',
            field=models.CharField(blank=True, choices=[('MAIN', 'MAIN'), ('SECONDARY', 'SECONDARY'), ('INACTIVE', 'INACTIVE')], max_length=25, null=True),
        ),
    ]
