# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20170410_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='learning_container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer'),
        ),
    ]
