# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20170331_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Structure'),
        ),
    ]
