# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_employee_facultyadministrator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyadministrator',
            options={'permissions': (('is_faculty_administrator', 'Is faculty administrator'),)},
        ),
    ]
