# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 06:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_auto_20170411_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'permissions': (('is_entity_manager', 'Is entity manager '),),
            },
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_draft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='scores_must_be_between_0_and_20'), django.core.validators.MaxValueValidator(20, message='scores_must_be_between_0_and_20')]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='scores_must_be_between_0_and_20'), django.core.validators.MaxValueValidator(20, message='scores_must_be_between_0_and_20')]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_reencoded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='scores_must_be_between_0_and_20'), django.core.validators.MaxValueValidator(20, message='scores_must_be_between_0_and_20')]),
        ),
        migrations.AddField(
            model_name='entitymanager',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person'),
        ),
        migrations.AddField(
            model_name='entitymanager',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Structure'),
        ),
    ]
