# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 08:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_auto_20170418_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examenrollment',
            name='score_draft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='scores_must_be_between_0_and_20'), django.core.validators.MaxValueValidator(20, message='scores_must_be_between_0_and_20')]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='scores_must_be_between_0_and_20'), django.core.validators.MaxValueValidator(20, message='scores_must_be_between_0_and_20')]),
        ),
        migrations.AlterField(
            model_name='examenrollment',
            name='score_reencoded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0, message='scores_must_be_between_0_and_20'), django.core.validators.MaxValueValidator(20, message='scores_must_be_between_0_and_20')]),
        ),
        migrations.AlterField(
            model_name='sessionexamdeadline',
            name='deadline_tutor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
