# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 07:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_auto_20170421_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionexam',
            name='offer_year',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.OfferYear'),
            preserve_default=False,
        ),
    ]
