# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_auto_20170421_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='global_id',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='registration_id',
            field=models.CharField(db_index=True, max_length=10, unique=True),
        ),
    ]
