# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0107_learningunit_learning_container'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningunit',
            name='learning_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainer'),
        ),
    ]
