# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-12 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_offeryear_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunitcomponent',
            name='coefficient_repetition',
        ),
        migrations.AddField(
            model_name='learningcomponentyear',
            name='planned_classes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
