# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0112_offeryear_offer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningcontainer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='type',
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='container_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'COURSE'), ('MASTER_THESIS', 'MASTER_THESIS'), ('INTERNSHIP', 'INTERNSHIP')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True, choices=[('DISSERTATION', 'DISSERTATION'), ('FULL', 'FULL'), ('MOBILITY', 'MOBILITY'), ('OTHER', 'OTHER'), ('PARTIM', 'PARTIM'), ('THESIS', 'THESIS')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
