# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0113_entity_entityaddress_entitylink_entityversion'),
        ('base', '0113_auto_20170508_1548'),
    ]

    operations = [
    ]
