# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_auto_20170512_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='type',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True,
                                   choices=[('MASTER_DISSERTATION', 'MASTER_DISSERTATION'), ('FULL', 'FULL'),
                                            ('MOBILITY', 'MOBILITY'), ('OTHER', 'OTHER'), ('PARTIM', 'PARTIM'),
                                            ('PHD_THESIS', 'PHD_THESIS')], max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='learningunityear',
            name='status',
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='activity_status',
            field=models.CharField(blank=True,
                                   choices=[('ACTIVE', 'ACTIVE'), ('PASSIVE', 'PASSIVE'), ('INACTIVE', 'INACTIVE')],
                                   max_length=20, null=True),
        ),
        migrations.RemoveField(
            model_name='learningcontainer',
            name='title',
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'COURSE'), ('DISSERTATION', 'DISSERTATION'),
                                                        ('INTERNSHIP', 'INTERNSHIP')], max_length=20, null=True),
        ),
    ]
