# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_auto_20170512_0859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='entityaddress',
            options={'verbose_name_plural': 'entity addresses'},
        ),
        migrations.AddField(
            model_name='entity',
            name='external_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_to_parent', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entitylink',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_to_children', to='base.Entity'),
        ),
    ]
