# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-15 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0114_auto_20170512_0859'),
        ('base', '0114_merge'),
    ]

    operations = [
    ]
