# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-16 08:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0115_auto_20170508_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'entities'},
        ),
        migrations.AlterModelOptions(
            name='entityaddress',
            options={'verbose_name_plural': 'entity addresses'},
        ),
    ]
