# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-24 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0121_auto_20170518_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningclass',
            name='learning_component',
        ),
        migrations.RemoveField(
            model_name='learningcomponent',
            name='learning_container',
        ),
        migrations.RemoveField(
            model_name='learningclassyear',
            name='learning_class',
        ),
        migrations.RemoveField(
            model_name='learningcomponentyear',
            name='learning_component',
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('STAGE', 'STAGE'), ('DISSERTATION', 'DISSERTATION'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES'), ('OTHER', 'OTHER')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='LearningClass',
        ),
        migrations.DeleteModel(
            name='LearningComponent',
        ),
    ]
