# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-29 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0122_auto_20170524_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('STAGE', 'STAGE'), ('DISSERTATION', 'DISSERTATION'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], max_length=30, null=True),
        ),
    ]
