# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0124_entity_models_update'),
        ('base', '0124_auto_20170530_1401'),
    ]

    operations = [
    ]
