# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-30 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0126_auto_20170530_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationaddress',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='organizationaddress',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
