# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0126_auto_20170530_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': (('can_post_entities_by_drf', 'Can post entities by DRF'),), 'verbose_name_plural': 'entities'},
        ),
    ]
