# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0127_auto_20170530_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='acronym_learning_unit',
            new_name='prefix',
        ),
    ]
