# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0128_auto_20170601_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
