# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0129_auto_20170601_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityaddress',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitylink',
            name='child',
        ),
        migrations.RemoveField(
            model_name='entitylink',
            name='parent',
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_of', to='base.Entity'),
        ),
        migrations.DeleteModel(
            name='EntityAddress',
        ),
        migrations.DeleteModel(
            name='EntityLink',
        ),
    ]
