# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0130_learningcontaineryear_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='type',
            field=models.CharField(blank=True, choices=[('LECTURING', 'LECTURING'), ('PRACTICAL_EXERCISES', 'PRACTICAL_EXERCISES')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='learningcontaineryear',
            name='container_type',
            field=models.CharField(blank=True, choices=[('COURSE', 'COURSE'), ('INTERNSHIP', 'INTERNSHIP'), ('DISSERTATION', 'DISSERTATION'), ('OTHER_COLLECTIVE', 'OTHER_COLLECTIVE'), ('OTHER_INDIVIDUAL', 'OTHER_INDIVIDUAL'), ('MASTER_THESIS', 'MASTER_THESIS'), ('EXTERNAL', 'EXTERNAL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM'), ('INTERNSHIP', 'INTERNSHIP'), ('TEACHING_INTERNSHIP', 'TEACHING_INTERNSHIP'), ('CLINICAL_INTERNSHIP', 'CLINICAL_INTERNSHIP'), ('PROFESSIONAL_INTERNSHIP', 'PROFESSIONAL_INTERNSHIP'), ('RESEARCH_INTERNSHIP', 'RESEARCH_INTERNSHIP')], max_length=50, null=True),
        ),
    ]
