# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-01 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0131_auto_20170602_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningclassyear',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='learningclassyear',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
