# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-02 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0133_auto_20170607_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityaddress',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitylink',
            name='child',
        ),
        migrations.RemoveField(
            model_name='entitylink',
            name='parent',
        ),
        migrations.AddField(
            model_name='entity',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='entityversion',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_of', to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Organization'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='end_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_of', to='base.Entity'),
        ),
        migrations.DeleteModel(
            name='EntityAddress',
        ),
        migrations.DeleteModel(
            name='EntityLink',
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='acronym',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity'),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='entityversion',
            name='entity_type',
            field=models.CharField(blank=True,
                                   choices=[('SECTOR', 'SECTOR'), ('FACULTY', 'FACULTY'), ('SCHOOL', 'SCHOOL'),
                                            ('INSTITUTE', 'INSTITUTE'), ('POLE', 'POLE'),
                                            ('DOCTORAL_COMMISSION', 'DOCTORAL_COMMISSION'), ('PLATFORM', 'PLATFORM'),
                                            ('LOGISTICS_ENTITY', 'LOGISTICS_ENTITY')],
                                   db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
