# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-16 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0134_entity_models_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitymanager',
            options={},
        ),
    ]
