# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-14 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0134_entity_models_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityComponentYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_volume_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hourly_volume_partial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityContainerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('REQUIREMENT_ENTITY', 'REQUIREMENT_ENTITY'), ('ALLOCATION_ENTITY', 'ALLOCATION_ENTITY'), ('ADDITIONAL_REQUIREMENT_ENTITY', 'ADDITIONAL_REQUIREMENT_ENTITY')], max_length=30)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Entity')),
                ('learning_container_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningContainerYear')),
            ],
        ),
        migrations.AddField(
            model_name='learningcontainer',
            name='auto_renewal_until',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entitycomponentyear',
            name='entity_container_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.EntityContainerYear'),
        ),
        migrations.AddField(
            model_name='entitycomponentyear',
            name='learning_component_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.LearningComponentYear'),
        ),
    ]
