# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0137_auto_20170620_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcontainer',
            name='start_year',
            field=models.IntegerField(null=True),
        ),
    ]
