# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-27 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0139_learningcontainer_start_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learningunitcomponentclass',
            old_name='learning_unit_year',
            new_name='learning_class_year',
        ),
    ]
