# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0141_auto_20170703_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribution',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='attribution',
            name='tutor',
        ),
        migrations.DeleteModel(
            name='Attribution',
        ),
    ]
