# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0143_educationgroup_educationgroupyear_groupelementyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='internship_subtype',
            field=models.CharField(blank=True, choices=[('TEACHING_INTERNSHIP', 'TEACHING_INTERNSHIP'), ('CLINICAL_INTERNSHIP', 'CLINICAL_INTERNSHIP'), ('PROFESSIONAL_INTERNSHIP', 'PROFESSIONAL_INTERNSHIP'), ('RESEARCH_INTERNSHIP', 'RESEARCH_INTERNSHIP')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]



