# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-01 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0144_auto_20170719_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunityear',
            name='activity_status',
        ),
        migrations.AlterField(
            model_name='learningunityear',
            name='subtype',
            field=models.CharField(blank=True, choices=[('FULL', 'FULL'), ('PARTIM', 'PARTIM')], max_length=50, null=True),
        ),
    ]
