# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0145_auto_20170801_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='national_id',
        ),
    ]
