# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-07 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0145_auto_20170801_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_access_student', 'Can access student'),)},
        ),
    ]
