# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-10 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0146_remove_person_national_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'permissions': (('can_access_student', 'Can access student'),)},
        ),
    ]
