# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0147_auto_20170810_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningcomponentyear',
            name='acronym',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
