# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0147_auto_20170810_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='entitycomponentyear',
            unique_together=set([('entity_container_year', 'learning_component_year')]),
        ),
    ]
