# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0148_auto_20170821_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcomponentyear',
            name='hourly_volume_partial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
