# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-30 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0148_auto_20170821_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunit',
            name='faculty_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningunit',
            name='other_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningunityear',
            name='session',
            field=models.CharField(blank=True, choices=[('P23', 'P23'), ('3', '3'), ('2', '2'), ('23', '23'), ('1', '1'), ('13', '13'), ('12', '12'), ('123', '123')], max_length=50, null=True),
        ),
    ]
