# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0149_auto_20170830_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='academic_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='base.Entity'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='academic_type',
            field=models.CharField(blank=True, choices=[('NON_ACADEMIC_OTHER', 'NON_ACADEMIC_OTHER'), ('NON_ACADEMIC_CREF', 'NON_ACADEMIC_CREF'), ('ACADEMIC', 'ACADEMIC')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='active',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('RE_REGISTRATION', 'RE_REGISTRATION')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='administration_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administration', to='base.Entity'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='concours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='diploma_focus',
            field=models.CharField(blank=True, choices=[('NO_PRINT', 'NO_PRINT'), ('IN_HEADING_2_OF_DIPLOMA', 'IN_HEADING_2_OF_DIPLOMA'), ('IN_EXPECTED_FORM', 'IN_EXPECTED_FORM')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='dissertation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='end_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='english_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='enrollment_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='base.Campus'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='exchange_comment',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='fundable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding_cud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding_guidance',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='funding_guidance_cud',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='internships',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='joint_diploma',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='main_teaching_campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching', to='base.Campus'),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='other_campus_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='other_language_activities',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO'), ('OPTIONAL', 'OPTIONAL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='professionnal_title',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='rate',
            field=models.CharField(blank=True, choices=[('RATE1', 'RATE1'), ('RATE2', 'RATE2'), ('RATE3', 'RATE3'), ('RATE4', 'RATE4'), ('RATE5', 'RATE5'), ('RATE6', 'RATE6'), ('RATE7', 'RATE7'), ('RATE8', 'RATE8'), ('RATE9', 'RATE9'), ('RATE10', 'RATE10'), ('RATE11', 'RATE11'), ('RATE12', 'RATE12'), ('RATE13', 'RATE13')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='schedule_type',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('SHIFT', 'SHIFT'), ('ADAPTED', 'ADAPTED')], default='DAILY', max_length=20),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='start_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='subtest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='title_printable',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='university_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offeryeardomain',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
