# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0150_auto_20170904_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_university_abroad',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_university_belgium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='educationgroupyear',
            name='inter_university_french_community',
            field=models.BooleanField(default=False),
        ),
    ]
