# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 07:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0150_learningcomponentyear_hourly_volume_partial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningunit',
            name='description',
        ),
    ]
