# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0150_auto_20170829_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entityaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='entityaddress',
            name='entity',
        ),
        migrations.AddField(
            model_name='entity',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='fax',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reference.Country'),
        ),
        migrations.DeleteModel(
            name='EntityAddress',
        ),
    ]
