# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0151_remove_learningunit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='highlight_title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
