# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0155_auto_20170908_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeryearentity',
            name='education_group_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.EducationGroupYear'),
        ),
    ]
