# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-19 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0156_offeryearentity_education_group_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningunityear',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Entity'),
        ),
    ]
