# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def _find_learningunitcomponent(LearningUnitComponent):
    return LearningUnitComponent.objects.filter(learning_component_year__isnull=True)


def _delete_attribution_charges(AttributionCharge, learningunitcomponent):
    attribution_charges = AttributionCharge.objects.filter(learning_unit_component=learningunitcomponent)
    for attribution_charge in attribution_charges:
        attribution_charge.delete()


def delete_learningunitcomponent(apps, schema_editor):
    LearningUnitComponent = apps.get_model('base', 'learningunitcomponent')
    AttributionCharge = apps.get_model('attribution', 'attributioncharge')

    learningunitcomponents = _find_learningunitcomponent(LearningUnitComponent)
    for learningunitcomponent in learningunitcomponents:
        attribution_charges = _delete_attribution_charges(AttributionCharge, learningunitcomponent)
        learningunitcomponent.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0157_entitymanager_entity'),
    ]

    operations = [
        migrations.RunPython(delete_learningunitcomponent),
    ]
