# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.db import migrations, connection


def _find_entity_managers():
    print('_find_entity_managers')
    with connection.cursor() as cursor:
        sql = " SELECT base_entitymanager.id as entitymanager_id, base_entitymanager.structure_id as structure_id,  base_entitymanager.entity_id " \
              " FROM base_entitymanager"
        cursor.execute(sql)
        return dictfetchall(cursor)

    return None

def _add_entity_manager_entity(entity_manager, entity_id):
    print('_add_entity_manager_entity')


    with connection.cursor() as cursor:
        sql = "UPDATE base_entitymanager set entity_id=%s where id=%s"
        cursor.execute(sql, [entity_id, entity_manager['entitymanager_id']])


def _find_structure_code(an_id):
    print('_find_structure_code')
    with connection.cursor() as cursor:
        sql = " SELECT base_structure.* " \
              " FROM base_structure where id = %s"
        cursor.execute(sql, [an_id])
        return dictfetchall(cursor)

    return None


def _find_entitites(acronym):
    print('_find_entitites')
    with connection.cursor() as cursor:
        sql = " SELECT base_entityversion.id, base_entityversion.entity_id FROM base_entityversion where acronym = %s "
        # sql = " SELECT base_entityversion.id, base_entityversion.entity_id FROM base_entityversion "
        cursor.execute(sql, [acronym])
        # cursor.execute(sql)
        return dictfetchall(cursor)

    return None


def _find_all_entitites():
    print('_find_entitites')
    with connection.cursor() as cursor:
        sql = " SELECT base_entityversion.id, base_entityversion.entity_id, base_entityversion.acronym FROM base_entityversion"
        # sql = " SELECT base_entityversion.id, base_entityversion.entity_id FROM base_entityversion "
        cursor.execute(sql)
        # cursor.execute(sql)
        return dictfetchall(cursor)

    return None

def entity_manager_entities(apps, schema_editor):
    entity_managers = _find_entity_managers()
    all_entitites = _find_all_entitites()
    dict_enti={}
    for ent in all_entitites:
        if not dict_enti.get(ent['acronym']):
            dict_enti[ent['acronym']]=ent['entity_id']

    for entity_manager in entity_managers:

        structure_acronym=None
        structures = _find_structure_code(entity_manager['structure_id'])
        for struct in structures:
            structure_acronym = struct['acronym']
            break
        print(structure_acronym)
        if structure_acronym:
            print(dict_enti[structure_acronym])
            _add_entity_manager_entity(entity_manager, dict_enti[structure_acronym])


def dictfetchall(cursor):
    """Returns all rows from a cursor as a dict"""
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
        ]


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0156_entitymanager_entity'),
    ]

    operations = [
        migrations.RunPython(entity_manager_entities),
    ]
