# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 12:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0157_entitymanager_entity'),
    ]

    operations = [
        migrations.RunSQL(
            "delete from base_learningunitcomponent where base_learningunitcomponent.learning_component_year_id is null;"
        ),
    ]