# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0158_auto_20170921_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationgroup',
            options={'permissions': (('can_access_education_group', 'Can access education_group'),)},
        ),
    ]
