# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-03 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0162_educationgroup_permissions'),
        ('base', '0157_auto_20170919_1116'),
    ]

    operations = [
    ]
