# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0163_auto_20170919_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationgroupyear',
            name='category',
            field=models.CharField(blank=True, choices=[('TRAINING', 'TRAINING'), ('MINI_TRAINING', 'MINI_TRAINING'), ('GROUP', 'GROUP')], max_length=20, null=True),
        ),
    ]
