# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0164_educationgroupyear_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupelementyear',
            name='learning_unit_year',
        ),
        migrations.RemoveField(
            model_name='groupelementyear',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='groupelementyear',
            name='child_leaf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_leaf', to='base.LearningUnitYear'),
        ),
    ]
