# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 14:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0024_documentfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAssistant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=12)),
                ('fulltime_equivalent', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sap_id', models.CharField(max_length=12)),
                ('entry_date', models.DateField()),
                ('end_date', models.DateField()),
                ('scale', models.CharField(max_length=3)),
                ('thesis_title', models.CharField(blank=True, max_length=255, null=True)),
                ('phd_inscription_date', models.DateField(blank=True, null=True)),
                ('confirmation_test_date', models.DateField(blank=True, null=True)),
                ('thesis_date', models.DateField(blank=True, null=True)),
                ('expected_phd_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('inscription', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('IN_PROGRESS', 'In progress')], default='YES', max_length=12)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_supervisor', to='base.Person')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('PHD', 'PhD'), ('TUTORING', 'Tutoring'), ('RESEARCH', 'Research')], max_length=20)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AcademicAssistant')),
            ],
        ),
        migrations.CreateModel(
            name='AssistantMandate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absences', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('other_status', models.CharField(blank=True, max_length=50, null=True)),
                ('renewal_type', models.CharField(choices=[('NORMAL', 'Normal'), ('EXCEPTIONAL', 'Exceptional')], default='NORMAL', max_length=12)),
                ('external_functions', models.TextField(blank=True, null=True)),
                ('external_contract', models.CharField(blank=True, max_length=255, null=True)),
                ('justification', models.TextField(blank=True, null=True)),
                ('state', models.CharField(choices=[('TO_DO', 'To do'), ('TRTS', 'Trts'), ('PHD_SUPERVISOR', 'PhD supervisor'), ('RESEARCH', 'Research'), ('SUPERVISION', 'Supervision'), ('VICE_RECTOR', 'Vice rector')], default='TO_DO', max_length=20)),
                ('tutoring_remark', models.TextField(blank=True, null=True)),
                ('activities_report_remark', models.TextField(blank=True, null=True)),
                ('research_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tutoring_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('service_activities_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('formation_activities_percent', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('internships', models.TextField(blank=True, null=True)),
                ('conferences', models.TextField(blank=True, null=True)),
                ('publications', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('framing', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('degrees', models.TextField(blank=True, null=True)),
                ('formations', models.TextField(blank=True, null=True)),
                ('faculty_representation', models.PositiveIntegerField(default=0)),
                ('institute_representation', models.PositiveIntegerField(default=0)),
                ('sector_representation', models.PositiveIntegerField(default=0)),
                ('governing_body_representation', models.PositiveIntegerField(default=0)),
                ('corsci_representation', models.PositiveIntegerField(default=0)),
                ('students_service', models.PositiveIntegerField(default=0)),
                ('infrastructure_mgmt_service', models.PositiveIntegerField(default=0)),
                ('events_organisation_service', models.PositiveIntegerField(default=0)),
                ('publishing_field_service', models.PositiveIntegerField(default=0)),
                ('scientific_jury_service', models.PositiveIntegerField(default=0)),
                ('appeal', models.CharField(choices=[('NONE', 'N/A'), ('POSITIVE_APPEAL', 'Positive appeal'), ('NEGATIVE_APPEAL', 'Negative appeal'), ('APPEAL_IN_PROGRESS', 'Appeal in progress'), ('NO_APPEAL', 'No appeal')], default='NONE', max_length=20)),
                ('special', models.BooleanField(default=False)),
                ('contract_duration', models.CharField(max_length=30)),
                ('contract_duration_fte', models.CharField(max_length=30)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AcademicAssistant')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(choices=[('FAVORABLE', 'Favorable'), ('CONDITIONAL', 'Conditional'), ('UNFAVOURABLE', 'Unfavourable')], max_length=20)),
                ('justification', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('confidential', models.TextField(blank=True, null=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AssistantMandate')),
            ],
        ),
        migrations.CreateModel(
            name='TutoringLearningUnitYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('sessions_number', models.PositiveIntegerField(blank=True, null=True)),
                ('series_number', models.PositiveIntegerField(blank=True, null=True)),
                ('face_to_face_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('attendees', models.PositiveIntegerField(blank=True, null=True)),
                ('preparation_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('exams_supervision_duration', models.PositiveIntegerField(blank=True, null=True)),
                ('mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AssistantMandate')),
            ],
        ),
        migrations.AddField(
            model_name='assistantdocument',
            name='mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AssistantMandate'),
        ),
    ]
