# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-19 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantmandate',
            name='service_activities_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutoringlearningunityear',
            name='others_delivery',
            field=models.TextField(blank=True, null=True),
        ),
    ]
