# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-06 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_assistantmandate_academic_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], max_length=10, null=True),
        ),
    ]
