# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20160516_2107'),
        ('assistant', '0004_auto_20160506_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='MandateStructures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant_mandate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AcademicAssistant')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Structure')),
            ],
        ),
    ]
