# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 18:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_mandatestructures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicassistant',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='academicassistant',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='academicassistant',
            name='fulltime_equivalent',
        ),
        migrations.RemoveField(
            model_name='academicassistant',
            name='position_id',
        ),
        migrations.RemoveField(
            model_name='academicassistant',
            name='sap_id',
        ),
        migrations.RemoveField(
            model_name='academicassistant',
            name='scale',
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='assistant_type',
            field=models.CharField(choices=[('ASSISTANT', 'Assistant'), ('TEACHING_ASSISTANT', 'Teaching assistant')], default='ASSISTANT', max_length=20),
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 2, 18, 28, 17, 494727, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='entry_date',
            field=models.DateField(default=datetime.datetime(2016, 6, 2, 18, 28, 20, 502601, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='fulltime_equivalent',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='grade',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='position_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='sap_id',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assistantmandate',
            name='scale',
            field=models.CharField(default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assistantmandate',
            name='state',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('TO_DO', 'To do'), ('TRTS', 'Trts'), ('PHD_SUPERVISOR', 'PhD supervisor'), ('RESEARCH', 'Research'), ('SUPERVISION', 'Supervision'), ('VICE_RECTOR', 'Vice rector')], default='TO_DO', max_length=20),
        ),
    ]
