# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 08:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_auto_20160602_2028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MandateStructures',
            new_name='MandateStructure',
        ),
        migrations.AlterField(
            model_name='mandatestructure',
            name='assistant_mandate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.AssistantMandate'),
        ),
    ]
