# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-07 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0007_auto_20160607_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PHD_SUPERVISOR', 'PhD Supervisor'), ('SUPERVISION', 'Supervision'), ('RESEARCH', 'Research'), ('SECTOR_VICE_RECTOR', 'Sector Vice-Rector')], max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Person')),
                ('structure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Structure')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='assistant.Reviewer'),
            preserve_default=False,
        ),
    ]
