# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_auto_20160610_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='has_delegate',
        ),
        migrations.AddField(
            model_name='reviewer',
            name='delegate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.Reviewer'),
        ),
    ]
