# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-13 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'phd_supervisor'), ('SUPERVISION', 'supervision'), ('RESEARCH', 'research'), ('SECTOR_VICE_RECTOR', 'sector_vice_rector'), ('SECTOR_VICE_RECTOR_ASSISTANT', 'sector_vice_rector_assistant')], max_length=30),
        ),
    ]
