# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_tutoringlearningunityear_learning_unit_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewer',
            name='delegate_of',
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'phd_supervisor'), ('SUPERVISION', 'supervision'), ('SUPERVISION_ASSISTANT', 'supervision_assistant'), ('RESEARCH', 'research'), ('RESEARCH_ASSISTANT', 'research_assistant'), ('SECTOR_VICE_RECTOR', 'sector_vice_rector'), ('SECTOR_VICE_RECTOR_ASSISTANT', 'sector_vice_rector_assistant')], max_length=20),
        ),
    ]
