# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_auto_20160714_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmandate',
            name='state',
            field=models.CharField(choices=[('DECLINED', 'Declined'), ('TO_DO', 'To do'), ('TRTS', 'Trts'), ('PHD_SUPERVISOR', 'PhD supervisor'), ('RESEARCH', 'Research'), ('SUPERVISION', 'Supervision'), ('VICE_RECTOR', 'Vice rector'), ('DONE', 'Done')], default='TO_DO', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='changed',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.Reviewer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('DONE', 'Done')], max_length=15, null=True),
        ),
    ]
