# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0018_auto_20160812_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantmandate',
            name='grade',
            field=models.CharField(max_length=40),
        ),
    ]
