# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-09 13:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20170120_1615'),
        ('assistant', '0020_auto_20161019_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('type', models.CharField(choices=[('TO_ALL_ASSISTANTS', 'TO_ALL_ASSISTANTS'), ('TO_ALL_DEANS', 'TO_ALL_DEANS'), ('TO_PHD_SUPERVISOR', 'TO_PHD_SUPERVISOR'), ('TO_ONE_DEAN', 'TO_ONE_DEAN')], max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.AcademicYear')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Manager')),
            ],
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'PHD_SUPERVISOR'), ('SUPERVISION', 'SUPERVISION'), ('SUPERVISION_ASSISTANT', 'SUPERVISION_ASSISTANT'), ('RESEARCH', 'RESEARCH'), ('RESEARCH_ASSISTANT', 'RESEARCH_ASSISTANT'), ('SECTOR_VICE_RECTOR', 'SECTOR_VICE_RECTOR'), ('SECTOR_VICE_RECTOR_ASSISTANT', 'SECTOR_VICE_RECTOR_ASSISTANT')], max_length=30),
        ),
    ]
