# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-13 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0021_auto_20170209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advice',
            field=models.CharField(choices=[('FAVORABLE', 'FAVORABLE'), ('CONDITIONAL', 'CONDITIONAL'), ('UNFAVOURABLE', 'UNFAVOURABLE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'PHD_SUPERVISOR'), ('SUPERVISION', 'SUPERVISION'), ('SUPERVISION_ASSISTANT', 'SUPERVISION_ASSISTANT'), ('RESEARCH', 'RESEARCH'), ('RESEARCH_ASSISTANT', 'RESEARCH_ASSISTANT'), ('VICE_RECTOR', 'VICE_RECTOR'), ('VICE_RECTOR_ASSISTANT', 'VICE_RECTOR_ASSISTANT')], max_length=30),
        ),
    ]
