# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-25 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0021_auto_20170209_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='advice',
            field=models.CharField(choices=[('FAVORABLE', 'FAVORABLE'), ('CONDITIONAL', 'CONDITIONAL'), ('UNFAVOURABLE', 'UNFAVOURABLE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'IN_PROGRESS'), ('DONE', 'DONE')], max_length=15, null=True),
        ),
    ]
