# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0022_auto_20170326_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='role',
            field=models.CharField(choices=[('PHD_SUPERVISOR', 'PHD_SUPERVISOR'), ('SUPERVISION', 'SUPERVISION'), ('SUPERVISION_ASSISTANT', 'SUPERVISION_ASSISTANT'), ('RESEARCH', 'RESEARCH'), ('RESEARCH_ASSISTANT', 'RESEARCH_ASSISTANT'), ('VICE_RECTOR', 'VICE_RECTOR'), ('VICE_RECTOR_ASSISTANT', 'VICE_RECTOR_ASSISTANT')], max_length=30),
        ),
    ]
