# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-20 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0023_auto_20170420_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicassistant',
            name='inscription',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('IN_PROGRESS', 'IN_PROGRESS')], default='YES', max_length=12),
        ),
    ]
