# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-05 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0024_auto_20170420_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantmandate',
            name='grade',
        ),
    ]
