# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0026_auto_20170508_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assistantmandate',
            name='degrees',
        ),
    ]
