# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-31 14:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0027_remove_assistantmandate_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='assistants_ending_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 14, 21, 58, 950224, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='assistants_starting_date',
            field=models.DateField(default=datetime.datetime(2017, 5, 31, 14, 22, 2, 238824, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
