# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0028_auto_20170531_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('TO_ALL_ASSISTANTS', 'TO_ALL_ASSISTANTS'), ('TO_ALL_DEANS', 'TO_ALL_DEANS'), ('TO_PHD_SUPERVISOR', 'TO_PHD_SUPERVISOR'), ('TO_ONE_DEAN', 'TO_ONE_DEAN'), ('TO_ALL_REVIEWERS', 'TO_ALL_REVIEWERS')], max_length=20),
        ),
    ]
