# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-28 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0031_auto_20170921_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mandatestructure',
            name='assistant_mandate',
        ),
        migrations.RemoveField(
            model_name='mandatestructure',
            name='structure',
        ),
        migrations.DeleteModel(
            name='MandateStructure',
        ),
    ]
