= Open Student Information System : Stages de médecine
Hildeberto Mendonça <hildeberto.mendonca@uclouvain.be>
v0.7.0, 2018-04-23
:doctype: book
:encoding: utf-8
:toc: left
:toclevels: 4
:numbered:

:sectnums!:

== Introduction

L'objectif de ce document est de communiquer le métier de gestion des stages au sein de la faculté de médecine et de décrire le fonctionnement de l'application développée dans le but d'optimiser la charge de travail consacrée à l'affectation des stages.

Le document est organisé en deux parties:

1. *Les fonctionalités*: la description du métier et comment celui-ci est couvert par l'application. Cette partie se concentre sur les activités du personnel administratif sur la gestion des stages de médecine.

2. *La platforme*: la description technique de l'architecture logicielle, destinée aux développeurs qui prendront en charge la maintenance technique de l'application.

Ce document est très important pour le bon déroulement de l'application. Il s'est récemment prouvé utile pour la création annuelle de la cohorte par les utilisateurs, qui ont pu réaliser cela en toute autonomie. Chaque nouvelle personne qui débarque dans le projet se trouve confrontée aux mêmes questions ses prédécesseurs. Si celui-ce est bien fait et bien maintenu, ce document aidera la faculté de médecine à faire évoluer son application proprement et continuellement, indépendamment des changements apportés au sein de l'équipe, tout en protégeant l'investissement déjà accompli. Pour que la documentation soit tenue à jour, le personnel technique doit l'actualiser chaque fois qu'une modification affecte le comportement de l'application. De cette façon, documenter ne devient pas une tâche laborieuse.

=== Le contexte

La *Faculté de médecine et médecine dentaire* (MEDE) fait partie du *Secteur des sciences de la santé* (SSS) de *l'Université catholique de Louvain* (UCL). Leurs activités sont, en général, réalisées au campus de Woluwe, Bruxelles.

Les stages sont considérés comme une activité d'unité d'enseignement dans le programme annuelle de formation de l'université. C'est une activité complexe, gérée par la *Commission de gestion des stages en médecine*, qui s’assure de la qualité des stages proposés aux étudiants et fait des propositions pour leur amélioration, tant d'un point de vue de la qualité pédagogique que de celui du confort matériel et de la sécurité. Elle entretient une coordination avec le responsable académique mobilité et le responsable de la coopération avec les pays en voie de développement pour l’organisation de stages à l’étranger. Elle veille à une répartition des étudiants parmi les lieux de stages conforme à la justice, aux besoins pédagogiques individuels des étudiants, en tenant compte des besoins particuliers des divers maîtres de stage, et en veillant à un juste équilibre entre les stages extra-muros et ceux ayant lieu au sein même des cliniques universitaires. Elle apporte aux maîtres de stage son assistance pour l’évaluation des étudiants qui leur sont confiés.

=== Les acteurs

Les acteurs impliqués dans la gestion des stages sont:

* les *étudiants* inscrits aux programmes de master en médecine
* les *gestionnaires* des stages: le doyen et le personnel administratif
* *l'administrateur de système*: la personne avec un rôle technique et bien informé sur le fonctionnement de l'application.
* *l'application*: le logiciel responsable pour la gestion de données et des affectations automatiques.

Les acteurs sont classés en deux rôles bien distincts:

* **Gestionnaire des stages**: L'accès est limité à l'application back office. Le back-office n'est accessible que dans le réseau de l'université.
* **Étudiant**: L'accès est limité à l'application front-office.
* **Administrateur**: Accès à l'administration des données bruts pour la resolution des problèmes non anticipés.

Une explication détaillée des applications back-office et front-office est disponible dans le chapitre 2.

:sectnums:

include::features_fr.adoc[]

include::platform_fr.adoc[]
