= Open Student Information System : Stages de médecine
Hildeberto Mendonça <hildeberto.mendonca@uclouvain.be>
v0.4.5, 2018-01-31
:doctype: book
:encoding: utf-8
:toc: left
:toclevels: 4
:numbered:

:sectnums!:

== Introduction

L'objectif de ce document est de communiquer le métier de gestion des stages au sein de la faculté de médecine et décrire le fonctionnement de l'application développé dans le but de optimiser la charge de travail consacré a l'affectation des stages.

Chaque nouvelle personne qui débarque dans le projet rencontre le défi de tout comprendre en posant les mêmes questions encore et encore. Si bien fait et bien maintenu, ce document aidera la faculté de médecine à évoluer son application proprement et continuellement, indépendant du changement de l'équipe, tout en protégeant l'investissement déjà fait.

Le document est organisé en deux parties.

=== Le contexte

La *Faculté de médecine et médecine dentaire* (MEDE) faire partit du *Secteur des sciences de la santé* (SSS) de *l'Université catholique de Louvain* (UCL). Leurs activités sont, en général, réaliser au campus de Wolluwé, Bruxelles.

Les stages sont prévu comment une activité d'unité d'enseignement dans le programme annuelle de formation de l'université. C'est une activité complexe, gérer par la *Commission de gestion des stages en médecine*, qui s’assure de la qualité des stages proposés aux étudiants et fait des propositions pour l’amélioration des stages, tant pour la qualité pédagogique que pour le confort matériel et la sécurité. Elle entretient une coordination avec le responsable académique mobilité et avec le responsable de la coopération avec les pays en voie de développement pour l’organisation de stages à l’étranger. Elle veille à une répartition des étudiants parmi les lieux de stages conforme à la justice, aux besoins pédagogiques individuels des étudiants, en tenant compte des besoins particuliers des divers maîtres de stage, et en veillant à un juste équilibre entre les stages extra-muros et dans les cliniques universitaires. Elle apporte aux maîtres de stage son assistance pour l’évaluation des étudiants qui leur sont confiés.

=== Les acteurs

Les acteurs impliqué dans la gestion des stages sont:

* les étudiants inscrits aux programmes de master en médecine
* les membres de la faculté: le doyen et le personnel administratif
* l'administrateur de système: la personne avec un role technique et bien informé par rapport au fonctionnement de l'application.

Les acteurs sont classés en deux rôles bien distincts:

* **Gestionnaire des stages**: L'accès est limité à l'application backoffice.
* **Étudiant**: L'accès est limité à l'application frontoffice.
* **Administrateur**: Accès à l'administration de données brut pour la resolution des problèmes techniques.

Une explication detaillé des applications backoffice et frontoffice est disponible dans la section 2.

:sectnums:

include::features_fr.adoc[]

include::technical_fr.adoc[]
