import academic_year
import attribution
import exam
import exam_enrollment
import learning_unit
import learning_unit_enrollment
import learning_unit_year
import offer
import offer_enrollment
import offer_year
import structure
import person
import student
import tutor
